//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.Affiliation;
import org.springframework.social.orcid.jaxb.beans.AffiliationType;
import org.springframework.social.orcid.jaxb.beans.CreatedDate;
import org.springframework.social.orcid.jaxb.beans.FuzzyDate;
import org.springframework.social.orcid.jaxb.beans.LastModifiedDate;
import org.springframework.social.orcid.jaxb.beans.Organization;
import org.springframework.social.orcid.jaxb.beans.Source;
import org.springframework.social.orcid.jaxb.beans.Visibility;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "departmentName",
    "roleTitle",
    "startDate",
    "endDate",
    "organization",
    "source",
    "createdDate",
    "lastModifiedDate"
})
@XmlRootElement(name = "affiliation")
public class AffiliationImpl
    implements Affiliation
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected AffiliationType type;
    @XmlElement(name = "department-name")
    protected String departmentName;
    @XmlElement(name = "role-title")
    protected String roleTitle;
    @XmlElement(name = "start-date", type = FuzzyDateImpl.class)
    protected FuzzyDateImpl startDate;
    @XmlElement(name = "end-date", type = FuzzyDateImpl.class)
    protected FuzzyDateImpl endDate;
    @XmlElement(required = true, type = OrganizationImpl.class)
    protected OrganizationImpl organization;
    @XmlElement(type = SourceImpl.class)
    protected SourceImpl source;
    @XmlElement(name = "created-date", type = CreatedDateImpl.class)
    protected CreatedDateImpl createdDate;
    @XmlElement(name = "last-modified-date", type = LastModifiedDateImpl.class)
    protected LastModifiedDateImpl lastModifiedDate;
    @XmlAttribute(name = "visibility")
    protected Visibility visibility;
    @XmlAttribute(name = "put-code")
    protected BigInteger putCode;

    public AffiliationType getType() {
        return type;
    }

    public void setType(AffiliationType value) {
        this.type = value;
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public void setDepartmentName(String value) {
        this.departmentName = value;
    }

    public String getRoleTitle() {
        return roleTitle;
    }

    public void setRoleTitle(String value) {
        this.roleTitle = value;
    }

    public FuzzyDate getStartDate() {
        return startDate;
    }

    public void setStartDate(FuzzyDate value) {
        this.startDate = ((FuzzyDateImpl) value);
    }

    public FuzzyDate getEndDate() {
        return endDate;
    }

    public void setEndDate(FuzzyDate value) {
        this.endDate = ((FuzzyDateImpl) value);
    }

    public Organization getOrganization() {
        return organization;
    }

    public void setOrganization(Organization value) {
        this.organization = ((OrganizationImpl) value);
    }

    public Source getSource() {
        return source;
    }

    public void setSource(Source value) {
        this.source = ((SourceImpl) value);
    }

    public CreatedDate getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(CreatedDate value) {
        this.createdDate = ((CreatedDateImpl) value);
    }

    public LastModifiedDate getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(LastModifiedDate value) {
        this.lastModifiedDate = ((LastModifiedDateImpl) value);
    }

    public Visibility getVisibility() {
        return visibility;
    }

    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

    public BigInteger getPutCode() {
        return putCode;
    }

    public void setPutCode(BigInteger value) {
        this.putCode = value;
    }

}
