//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.ApplicationSummary;
import org.springframework.social.orcid.jaxb.beans.Applications;
import org.springframework.social.orcid.jaxb.beans.Visibility;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationSummaries"
})
@XmlRootElement(name = "applications")
public class ApplicationsImpl
    implements Applications
{

    @XmlElement(name = "application-summary", required = true, type = ApplicationSummaryImpl.class)
    protected List<ApplicationSummary> applicationSummaries;
    @XmlAttribute(name = "visibility")
    protected Visibility visibility;

    public List<ApplicationSummary> getApplicationSummaries() {
        if (applicationSummaries == null) {
            applicationSummaries = new ArrayList<ApplicationSummary>();
        }
        return this.applicationSummaries;
    }

    public Visibility getVisibility() {
        return visibility;
    }

    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

}
