//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import org.springframework.social.orcid.jaxb.beans.Email;
import org.springframework.social.orcid.jaxb.beans.Visibility;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "email")
public class EmailImpl
    implements Email
{

    @XmlValue
    protected String value;
    @XmlAttribute(name = "primary")
    protected Boolean primary;
    @XmlAttribute(name = "current")
    protected Boolean current;
    @XmlAttribute(name = "verified")
    protected Boolean verified;
    @XmlAttribute(name = "source")
    protected String source;
    @XmlAttribute(name = "source-client-id")
    protected String sourceClientId;
    @XmlAttribute(name = "visibility")
    protected Visibility visibility;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public boolean isPrimary() {
        if (primary == null) {
            return true;
        } else {
            return primary;
        }
    }

    public void setPrimary(Boolean value) {
        this.primary = value;
    }

    public boolean isCurrent() {
        if (current == null) {
            return true;
        } else {
            return current;
        }
    }

    public void setCurrent(Boolean value) {
        this.current = value;
    }

    public boolean isVerified() {
        if (verified == null) {
            return false;
        } else {
            return verified;
        }
    }

    public void setVerified(Boolean value) {
        this.verified = value;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String value) {
        this.source = value;
    }

    public String getSourceClientId() {
        return sourceClientId;
    }

    public void setSourceClientId(String value) {
        this.sourceClientId = value;
    }

    public Visibility getVisibility() {
        return visibility;
    }

    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

}
