//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.FundingContributor;
import org.springframework.social.orcid.jaxb.beans.FundingContributors;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundingContributors"
})
@XmlRootElement(name = "funding-contributors")
public class FundingContributorsImpl
    implements FundingContributors
{

    @XmlElement(name = "funding-contributor", type = FundingContributorImpl.class)
    protected List<FundingContributor> fundingContributors;

    public List<FundingContributor> getFundingContributors() {
        if (fundingContributors == null) {
            fundingContributors = new ArrayList<FundingContributor>();
        }
        return this.fundingContributors;
    }

}
