//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.Funding;
import org.springframework.social.orcid.jaxb.beans.FundingList;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundings"
})
@XmlRootElement(name = "funding-list")
public class FundingListImpl
    implements FundingList
{

    @XmlElement(name = "funding", type = FundingImpl.class)
    protected List<Funding> fundings;

    public List<Funding> getFundings() {
        if (fundings == null) {
            fundings = new ArrayList<Funding>();
        }
        return this.fundings;
    }

}
