//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import org.springframework.social.orcid.jaxb.beans.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.hr.orcid.jaxb.beans.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SourceOrcid_QNAME = new QName("http://www.orcid.org/ns/orcid", "source-orcid");
    private final static QName _SendEmailFrequencyDays_QNAME = new QName("http://www.orcid.org/ns/orcid", "send-email-frequency-days");
    private final static QName _ShortDescription_QNAME = new QName("http://www.orcid.org/ns/orcid", "short-description");
    private final static QName _OrcidIdentifier_QNAME = new QName("http://www.orcid.org/ns/orcid", "orcid-identifier");
    private final static QName _Locale_QNAME = new QName("http://www.orcid.org/ns/orcid", "locale");
    private final static QName _WorkExternalIdentifierType_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-external-identifier-type");
    private final static QName _WorkType_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-type");
    private final static QName _FundingExternalIdentifierType_QNAME = new QName("http://www.orcid.org/ns/orcid", "funding-external-identifier-type");
    private final static QName _MessageVersion_QNAME = new QName("http://www.orcid.org/ns/orcid", "message-version");
    private final static QName _FundingContributorRole_QNAME = new QName("http://www.orcid.org/ns/orcid", "funding-contributor-role");
    private final static QName _ApplicationOrcid_QNAME = new QName("http://www.orcid.org/ns/orcid", "application-orcid");
    private final static QName _SendMemberUpdateRequests_QNAME = new QName("http://www.orcid.org/ns/orcid", "send-member-update-requests");
    private final static QName _DisambiguatedOrganizationIdentifier_QNAME = new QName("http://www.orcid.org/ns/orcid", "disambiguated-organization-identifier");
    private final static QName _OrganizationDefinedType_QNAME = new QName("http://www.orcid.org/ns/orcid", "organization-defined-type");
    private final static QName _FundingType_QNAME = new QName("http://www.orcid.org/ns/orcid", "funding-type");
    private final static QName _SalesforceId_QNAME = new QName("http://www.orcid.org/ns/orcid", "salesforce-id");
    private final static QName _ContributorSequence_QNAME = new QName("http://www.orcid.org/ns/orcid", "contributor-sequence");
    private final static QName _DisambiguationSource_QNAME = new QName("http://www.orcid.org/ns/orcid", "disambiguation-source");
    private final static QName _ContributorOrcid_QNAME = new QName("http://www.orcid.org/ns/orcid", "contributor-orcid");
    private final static QName _Host_QNAME = new QName("http://www.orcid.org/ns/orcid", "host");
    private final static QName _Path_QNAME = new QName("http://www.orcid.org/ns/orcid", "path");
    private final static QName _WorkExternalIdentifierId_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-external-identifier-id");
    private final static QName _ContributorRole_QNAME = new QName("http://www.orcid.org/ns/orcid", "contributor-role");
    private final static QName _WorkSource_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-source");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.hr.orcid.jaxb.beans.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SecurityDetails }
     * 
     */
    public SecurityDetailsImpl createSecurityDetails() {
        return new SecurityDetailsImpl();
    }

    /**
     * Create an instance of {@link EncryptedPassword }
     * 
     */
    public EncryptedPasswordImpl createEncryptedPassword() {
        return new EncryptedPasswordImpl();
    }

    /**
     * Create an instance of {@link SecurityQuestionId }
     * 
     */
    public SecurityQuestionIdImpl createSecurityQuestionId() {
        return new SecurityQuestionIdImpl();
    }

    /**
     * Create an instance of {@link EncryptedSecurityAnswer }
     * 
     */
    public EncryptedSecurityAnswerImpl createEncryptedSecurityAnswer() {
        return new EncryptedSecurityAnswerImpl();
    }

    /**
     * Create an instance of {@link EncryptedVerificationCode }
     * 
     */
    public EncryptedVerificationCodeImpl createEncryptedVerificationCode() {
        return new EncryptedVerificationCodeImpl();
    }

    /**
     * Create an instance of {@link FundingContributorAttributes }
     * 
     */
    public FundingContributorAttributesImpl createFundingContributorAttributes() {
        return new FundingContributorAttributesImpl();
    }

    /**
     * Create an instance of {@link Year }
     * 
     */
    public YearImpl createYear() {
        return new YearImpl();
    }

    /**
     * Create an instance of {@link OrcidDeprecated }
     * 
     */
    public OrcidDeprecatedImpl createOrcidDeprecated() {
        return new OrcidDeprecatedImpl();
    }

    /**
     * Create an instance of {@link DeprecatedDate }
     * 
     */
    public DeprecatedDateImpl createDeprecatedDate() {
        return new DeprecatedDateImpl();
    }

    /**
     * Create an instance of {@link PrimaryRecord }
     * 
     */
    public PrimaryRecordImpl createPrimaryRecord() {
        return new PrimaryRecordImpl();
    }

    /**
     * Create an instance of {@link OrcidId }
     * 
     */
    public OrcidIdImpl createOrcidId() {
        return new OrcidIdImpl();
    }

    /**
     * Create an instance of {@link Claimed }
     * 
     */
    public ClaimedImpl createClaimed() {
        return new ClaimedImpl();
    }

    /**
     * Create an instance of {@link SourceReference }
     * 
     */
    public SourceReferenceImpl createSourceReference() {
        return new SourceReferenceImpl();
    }

    /**
     * Create an instance of {@link SourceDate }
     * 
     */
    public SourceDateImpl createSourceDate() {
        return new SourceDateImpl();
    }

    /**
     * Create an instance of {@link WorkExternalIdentifiers }
     * 
     */
    public WorkExternalIdentifiersImpl createWorkExternalIdentifiers() {
        return new WorkExternalIdentifiersImpl();
    }

    /**
     * Create an instance of {@link WorkExternalIdentifier }
     * 
     */
    public WorkExternalIdentifierImpl createWorkExternalIdentifier() {
        return new WorkExternalIdentifierImpl();
    }

    /**
     * Create an instance of {@link FundingContributors }
     * 
     */
    public FundingContributorsImpl createFundingContributors() {
        return new FundingContributorsImpl();
    }

    /**
     * Create an instance of {@link FundingContributor }
     * 
     */
    public FundingContributorImpl createFundingContributor() {
        return new FundingContributorImpl();
    }

    /**
     * Create an instance of {@link CreditName }
     * 
     */
    public CreditNameImpl createCreditName() {
        return new CreditNameImpl();
    }

    /**
     * Create an instance of {@link ContributorEmail }
     * 
     */
    public ContributorEmailImpl createContributorEmail() {
        return new ContributorEmailImpl();
    }

    /**
     * Create an instance of {@link OrcidWorks }
     * 
     */
    public OrcidWorksImpl createOrcidWorks() {
        return new OrcidWorksImpl();
    }

    /**
     * Create an instance of {@link OrcidWork }
     * 
     */
    public OrcidWorkImpl createOrcidWork() {
        return new OrcidWorkImpl();
    }

    /**
     * Create an instance of {@link WorkTitle }
     * 
     */
    public WorkTitleImpl createWorkTitle() {
        return new WorkTitleImpl();
    }

    /**
     * Create an instance of {@link Subtitle }
     * 
     */
    public SubtitleImpl createSubtitle() {
        return new SubtitleImpl();
    }

    /**
     * Create an instance of {@link TranslatedTitle }
     * 
     */
    public TranslatedTitleImpl createTranslatedTitle() {
        return new TranslatedTitleImpl();
    }

    /**
     * Create an instance of {@link StringWithLangCode }
     * 
     */
    public StringWithLangCodeImpl createStringWithLangCode() {
        return new StringWithLangCodeImpl();
    }

    /**
     * Create an instance of {@link JournalTitle }
     * 
     */
    public JournalTitleImpl createJournalTitle() {
        return new JournalTitleImpl();
    }

    /**
     * Create an instance of {@link WorkCitation }
     * 
     */
    public WorkCitationImpl createWorkCitation() {
        return new WorkCitationImpl();
    }

    /**
     * Create an instance of {@link PublicationDate }
     * 
     */
    public PublicationDateImpl createPublicationDate() {
        return new PublicationDateImpl();
    }

    /**
     * Create an instance of {@link FuzzyDate }
     * 
     */
    public FuzzyDateImpl createFuzzyDate() {
        return new FuzzyDateImpl();
    }

    /**
     * Create an instance of {@link Month }
     * 
     */
    public MonthImpl createMonth() {
        return new MonthImpl();
    }

    /**
     * Create an instance of {@link Day }
     * 
     */
    public DayImpl createDay() {
        return new DayImpl();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public UrlImpl createUrl() {
        return new UrlImpl();
    }

    /**
     * Create an instance of {@link WorkContributors }
     * 
     */
    public WorkContributorsImpl createWorkContributors() {
        return new WorkContributorsImpl();
    }

    /**
     * Create an instance of {@link Contributor }
     * 
     */
    public ContributorImpl createContributor() {
        return new ContributorImpl();
    }

    /**
     * Create an instance of {@link ContributorAttributes }
     * 
     */
    public ContributorAttributesImpl createContributorAttributes() {
        return new ContributorAttributesImpl();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public SourceImpl createSource() {
        return new SourceImpl();
    }

    /**
     * Create an instance of {@link SourceClientId }
     * 
     */
    public SourceClientIdImpl createSourceClientId() {
        return new SourceClientIdImpl();
    }

    /**
     * Create an instance of {@link SourceName }
     * 
     */
    public SourceNameImpl createSourceName() {
        return new SourceNameImpl();
    }

    /**
     * Create an instance of {@link CreatedDate }
     * 
     */
    public CreatedDateImpl createCreatedDate() {
        return new CreatedDateImpl();
    }

    /**
     * Create an instance of {@link LastModifiedDate }
     * 
     */
    public LastModifiedDateImpl createLastModifiedDate() {
        return new LastModifiedDateImpl();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public CountryImpl createCountry() {
        return new CountryImpl();
    }

    /**
     * Create an instance of {@link ApplicationSummary }
     * 
     */
    public ApplicationSummaryImpl createApplicationSummary() {
        return new ApplicationSummaryImpl();
    }

    /**
     * Create an instance of {@link ApplicationName }
     * 
     */
    public ApplicationNameImpl createApplicationName() {
        return new ApplicationNameImpl();
    }

    /**
     * Create an instance of {@link ApplicationWebsite }
     * 
     */
    public ApplicationWebsiteImpl createApplicationWebsite() {
        return new ApplicationWebsiteImpl();
    }

    /**
     * Create an instance of {@link ApprovalDate }
     * 
     */
    public ApprovalDateImpl createApprovalDate() {
        return new ApprovalDateImpl();
    }

    /**
     * Create an instance of {@link ScopePaths }
     * 
     */
    public ScopePathsImpl createScopePaths() {
        return new ScopePathsImpl();
    }

    /**
     * Create an instance of {@link ScopePath }
     * 
     */
    public ScopePathImpl createScopePath() {
        return new ScopePathImpl();
    }

    /**
     * Create an instance of {@link ExternalIdReference }
     * 
     */
    public ExternalIdReferenceImpl createExternalIdReference() {
        return new ExternalIdReferenceImpl();
    }

    /**
     * Create an instance of {@link FundingExternalIdentifier }
     * 
     */
    public FundingExternalIdentifierImpl createFundingExternalIdentifier() {
        return new FundingExternalIdentifierImpl();
    }

    /**
     * Create an instance of {@link ActivitiesVisibilityDefault }
     * 
     */
    public ActivitiesVisibilityDefaultImpl createActivitiesVisibilityDefault() {
        return new ActivitiesVisibilityDefaultImpl();
    }

    /**
     * Create an instance of {@link FundingList }
     * 
     */
    public FundingListImpl createFundingList() {
        return new FundingListImpl();
    }

    /**
     * Create an instance of {@link Funding }
     * 
     */
    public FundingImpl createFunding() {
        return new FundingImpl();
    }

    /**
     * Create an instance of {@link FundingTitle }
     * 
     */
    public FundingTitleImpl createFundingTitle() {
        return new FundingTitleImpl();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public AmountImpl createAmount() {
        return new AmountImpl();
    }

    /**
     * Create an instance of {@link FundingExternalIdentifiers }
     * 
     */
    public FundingExternalIdentifiersImpl createFundingExternalIdentifiers() {
        return new FundingExternalIdentifiersImpl();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public OrganizationImpl createOrganization() {
        return new OrganizationImpl();
    }

    /**
     * Create an instance of {@link OrganizationAddress }
     * 
     */
    public OrganizationAddressImpl createOrganizationAddress() {
        return new OrganizationAddressImpl();
    }

    /**
     * Create an instance of {@link DisambiguatedOrganization }
     * 
     */
    public DisambiguatedOrganizationImpl createDisambiguatedOrganization() {
        return new DisambiguatedOrganizationImpl();
    }

    /**
     * Create an instance of {@link DelegateSummary }
     * 
     */
    public DelegateSummaryImpl createDelegateSummary() {
        return new DelegateSummaryImpl();
    }

    /**
     * Create an instance of {@link SendChangeNotifications }
     * 
     */
    public SendChangeNotificationsImpl createSendChangeNotifications() {
        return new SendChangeNotificationsImpl();
    }

    /**
     * Create an instance of {@link OrcidPreferences }
     * 
     */
    public OrcidPreferencesImpl createOrcidPreferences() {
        return new OrcidPreferencesImpl();
    }

    /**
     * Create an instance of {@link RelevancyScore }
     * 
     */
    public RelevancyScoreImpl createRelevancyScore() {
        return new RelevancyScoreImpl();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public EmailImpl createEmail() {
        return new EmailImpl();
    }

    /**
     * Create an instance of {@link SubmissionDate }
     * 
     */
    public SubmissionDateImpl createSubmissionDate() {
        return new SubmissionDateImpl();
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     */
    public PreferencesImpl createPreferences() {
        return new PreferencesImpl();
    }

    /**
     * Create an instance of {@link SendOrcidNews }
     * 
     */
    public SendOrcidNewsImpl createSendOrcidNews() {
        return new SendOrcidNewsImpl();
    }

    /**
     * Create an instance of {@link DeveloperToolsEnabled }
     * 
     */
    public DeveloperToolsEnabledImpl createDeveloperToolsEnabled() {
        return new DeveloperToolsEnabledImpl();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public AddressImpl createAddress() {
        return new AddressImpl();
    }

    /**
     * Create an instance of {@link Biography }
     * 
     */
    public BiographyImpl createBiography() {
        return new BiographyImpl();
    }

    /**
     * Create an instance of {@link DelegationDetails }
     * 
     */
    public DelegationDetailsImpl createDelegationDetails() {
        return new DelegationDetailsImpl();
    }

    /**
     * Create an instance of {@link ExternalIdUrl }
     * 
     */
    public ExternalIdUrlImpl createExternalIdUrl() {
        return new ExternalIdUrlImpl();
    }

    /**
     * Create an instance of {@link CompletionDate }
     * 
     */
    public CompletionDateImpl createCompletionDate() {
        return new CompletionDateImpl();
    }

    /**
     * Create an instance of {@link OrcidMessage }
     * 
     */
    public OrcidMessageImpl createOrcidMessage() {
        return new OrcidMessageImpl();
    }

    /**
     * Create an instance of {@link ErrorDesc }
     * 
     */
    public ErrorDescImpl createErrorDesc() {
        return new ErrorDescImpl();
    }

    /**
     * Create an instance of {@link OrcidSearchResults }
     * 
     */
    public OrcidSearchResultsImpl createOrcidSearchResults() {
        return new OrcidSearchResultsImpl();
    }

    /**
     * Create an instance of {@link OrcidSearchResult }
     * 
     */
    public OrcidSearchResultImpl createOrcidSearchResult() {
        return new OrcidSearchResultImpl();
    }

    /**
     * Create an instance of {@link OrcidProfile }
     * 
     */
    public OrcidProfileImpl createOrcidProfile() {
        return new OrcidProfileImpl();
    }

    /**
     * Create an instance of {@link OrcidHistory }
     * 
     */
    public OrcidHistoryImpl createOrcidHistory() {
        return new OrcidHistoryImpl();
    }

    /**
     * Create an instance of {@link DeactivationDate }
     * 
     */
    public DeactivationDateImpl createDeactivationDate() {
        return new DeactivationDateImpl();
    }

    /**
     * Create an instance of {@link OrcidBio }
     * 
     */
    public OrcidBioImpl createOrcidBio() {
        return new OrcidBioImpl();
    }

    /**
     * Create an instance of {@link PersonalDetails }
     * 
     */
    public PersonalDetailsImpl createPersonalDetails() {
        return new PersonalDetailsImpl();
    }

    /**
     * Create an instance of {@link OtherNames }
     * 
     */
    public OtherNamesImpl createOtherNames() {
        return new OtherNamesImpl();
    }

    /**
     * Create an instance of {@link ResearcherUrls }
     * 
     */
    public ResearcherUrlsImpl createResearcherUrls() {
        return new ResearcherUrlsImpl();
    }

    /**
     * Create an instance of {@link ResearcherUrl }
     * 
     */
    public ResearcherUrlImpl createResearcherUrl() {
        return new ResearcherUrlImpl();
    }

    /**
     * Create an instance of {@link ContactDetails }
     * 
     */
    public ContactDetailsImpl createContactDetails() {
        return new ContactDetailsImpl();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public KeywordsImpl createKeywords() {
        return new KeywordsImpl();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public KeywordImpl createKeyword() {
        return new KeywordImpl();
    }

    /**
     * Create an instance of {@link ExternalIdentifiers }
     * 
     */
    public ExternalIdentifiersImpl createExternalIdentifiers() {
        return new ExternalIdentifiersImpl();
    }

    /**
     * Create an instance of {@link ExternalIdentifier }
     * 
     */
    public ExternalIdentifierImpl createExternalIdentifier() {
        return new ExternalIdentifierImpl();
    }

    /**
     * Create an instance of {@link ExternalIdCommonName }
     * 
     */
    public ExternalIdCommonNameImpl createExternalIdCommonName() {
        return new ExternalIdCommonNameImpl();
    }

    /**
     * Create an instance of {@link Delegation }
     * 
     */
    public DelegationImpl createDelegation() {
        return new DelegationImpl();
    }

    /**
     * Create an instance of {@link GivenPermissionTo }
     * 
     */
    public GivenPermissionToImpl createGivenPermissionTo() {
        return new GivenPermissionToImpl();
    }

    /**
     * Create an instance of {@link GivenPermissionBy }
     * 
     */
    public GivenPermissionByImpl createGivenPermissionBy() {
        return new GivenPermissionByImpl();
    }

    /**
     * Create an instance of {@link Applications }
     * 
     */
    public ApplicationsImpl createApplications() {
        return new ApplicationsImpl();
    }

    /**
     * Create an instance of {@link OrcidActivities }
     * 
     */
    public OrcidActivitiesImpl createOrcidActivities() {
        return new OrcidActivitiesImpl();
    }

    /**
     * Create an instance of {@link Affiliations }
     * 
     */
    public AffiliationsImpl createAffiliations() {
        return new AffiliationsImpl();
    }

    /**
     * Create an instance of {@link Affiliation }
     * 
     */
    public AffiliationImpl createAffiliation() {
        return new AffiliationImpl();
    }

    /**
     * Create an instance of {@link OrcidInternal }
     * 
     */
    public OrcidInternalImpl createOrcidInternal() {
        return new OrcidInternalImpl();
    }

    /**
     * Create an instance of {@link Orcid }
     * 
     */
    public OrcidImpl createOrcid() {
        return new OrcidImpl();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidIdImpl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "source-orcid")
    public JAXBElement<OrcidIdImpl> createSourceOrcid(OrcidIdImpl value) {
        return new JAXBElement<OrcidIdImpl>(_SourceOrcid_QNAME, OrcidIdImpl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "send-email-frequency-days")
    public JAXBElement<String> createSendEmailFrequencyDays(String value) {
        return new JAXBElement<String>(_SendEmailFrequencyDays_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "short-description")
    public JAXBElement<String> createShortDescription(String value) {
        return new JAXBElement<String>(_ShortDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidIdImpl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "orcid-identifier")
    public JAXBElement<OrcidIdImpl> createOrcidIdentifier(OrcidIdImpl value) {
        return new JAXBElement<OrcidIdImpl>(_OrcidIdentifier_QNAME, OrcidIdImpl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "locale")
    public JAXBElement<String> createLocale(String value) {
        return new JAXBElement<String>(_Locale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-external-identifier-type")
    public JAXBElement<String> createWorkExternalIdentifierType(String value) {
        return new JAXBElement<String>(_WorkExternalIdentifierType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-type")
    public JAXBElement<String> createWorkType(String value) {
        return new JAXBElement<String>(_WorkType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "funding-external-identifier-type")
    public JAXBElement<String> createFundingExternalIdentifierType(String value) {
        return new JAXBElement<String>(_FundingExternalIdentifierType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "message-version")
    public JAXBElement<String> createMessageVersion(String value) {
        return new JAXBElement<String>(_MessageVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "funding-contributor-role")
    public JAXBElement<String> createFundingContributorRole(String value) {
        return new JAXBElement<String>(_FundingContributorRole_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidIdImpl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "application-orcid")
    public JAXBElement<OrcidIdImpl> createApplicationOrcid(OrcidIdImpl value) {
        return new JAXBElement<OrcidIdImpl>(_ApplicationOrcid_QNAME, OrcidIdImpl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "send-member-update-requests")
    public JAXBElement<Boolean> createSendMemberUpdateRequests(Boolean value) {
        return new JAXBElement<Boolean>(_SendMemberUpdateRequests_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "disambiguated-organization-identifier")
    public JAXBElement<String> createDisambiguatedOrganizationIdentifier(String value) {
        return new JAXBElement<String>(_DisambiguatedOrganizationIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "organization-defined-type")
    public JAXBElement<String> createOrganizationDefinedType(String value) {
        return new JAXBElement<String>(_OrganizationDefinedType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "funding-type")
    public JAXBElement<String> createFundingType(String value) {
        return new JAXBElement<String>(_FundingType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "salesforce-id")
    public JAXBElement<String> createSalesforceId(String value) {
        return new JAXBElement<String>(_SalesforceId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "contributor-sequence")
    public JAXBElement<String> createContributorSequence(String value) {
        return new JAXBElement<String>(_ContributorSequence_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "disambiguation-source")
    public JAXBElement<String> createDisambiguationSource(String value) {
        return new JAXBElement<String>(_DisambiguationSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidIdImpl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "contributor-orcid")
    public JAXBElement<OrcidIdImpl> createContributorOrcid(OrcidIdImpl value) {
        return new JAXBElement<OrcidIdImpl>(_ContributorOrcid_QNAME, OrcidIdImpl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "host")
    public JAXBElement<String> createHost(String value) {
        return new JAXBElement<String>(_Host_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "path")
    public JAXBElement<String> createPath(String value) {
        return new JAXBElement<String>(_Path_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-external-identifier-id")
    public JAXBElement<String> createWorkExternalIdentifierId(String value) {
        return new JAXBElement<String>(_WorkExternalIdentifierId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "contributor-role")
    public JAXBElement<String> createContributorRole(String value) {
        return new JAXBElement<String>(_ContributorRole_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidIdImpl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-source")
    public JAXBElement<OrcidIdImpl> createWorkSource(OrcidIdImpl value) {
        return new JAXBElement<OrcidIdImpl>(_WorkSource_QNAME, OrcidIdImpl.class, null, value);
    }

}
