//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.DeprecatedDate;
import org.springframework.social.orcid.jaxb.beans.OrcidDeprecated;
import org.springframework.social.orcid.jaxb.beans.PrimaryRecord;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deprecatedDate",
    "primaryRecord"
})
@XmlRootElement(name = "orcid-deprecated")
public class OrcidDeprecatedImpl
    implements OrcidDeprecated
{

    @XmlElement(name = "deprecated-date", required = true, type = DeprecatedDateImpl.class)
    protected DeprecatedDateImpl deprecatedDate;
    @XmlElement(name = "primary-record", required = true, type = PrimaryRecordImpl.class)
    protected PrimaryRecordImpl primaryRecord;

    public DeprecatedDate getDeprecatedDate() {
        return deprecatedDate;
    }

    public void setDeprecatedDate(DeprecatedDate value) {
        this.deprecatedDate = ((DeprecatedDateImpl) value);
    }

    public PrimaryRecord getPrimaryRecord() {
        return primaryRecord;
    }

    public void setPrimaryRecord(PrimaryRecord value) {
        this.primaryRecord = ((PrimaryRecordImpl) value);
    }

}
