//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.OrcidId;
import org.springframework.social.orcid.jaxb.beans.PrimaryRecord;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orcidIdentifier"
})
@XmlRootElement(name = "primary-record")
public class PrimaryRecordImpl
    implements PrimaryRecord
{

    @XmlElement(name = "orcid-identifier", required = true, type = OrcidIdImpl.class)
    protected OrcidIdImpl orcidIdentifier;

    public OrcidId getOrcidIdentifier() {
        return orcidIdentifier;
    }

    public void setOrcidIdentifier(OrcidId value) {
        this.orcidIdentifier = ((OrcidIdImpl) value);
    }

}
