//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.OrcidId;
import org.springframework.social.orcid.jaxb.beans.Source;
import org.springframework.social.orcid.jaxb.beans.SourceClientId;
import org.springframework.social.orcid.jaxb.beans.SourceDate;
import org.springframework.social.orcid.jaxb.beans.SourceName;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceClientId",
    "sourceOrcid",
    "sourceName",
    "sourceDate"
})
@XmlRootElement(name = "source")
public class SourceImpl
    implements Source
{

    @XmlElement(name = "source-client-id", type = SourceClientIdImpl.class)
    protected SourceClientIdImpl sourceClientId;
    @XmlElement(name = "source-orcid", type = OrcidIdImpl.class)
    protected OrcidIdImpl sourceOrcid;
    @XmlElement(name = "source-name", type = SourceNameImpl.class)
    protected SourceNameImpl sourceName;
    @XmlElement(name = "source-date", type = SourceDateImpl.class)
    protected SourceDateImpl sourceDate;

    public SourceClientId getSourceClientId() {
        return sourceClientId;
    }

    public void setSourceClientId(SourceClientId value) {
        this.sourceClientId = ((SourceClientIdImpl) value);
    }

    public OrcidId getSourceOrcid() {
        return sourceOrcid;
    }

    public void setSourceOrcid(OrcidId value) {
        this.sourceOrcid = ((OrcidIdImpl) value);
    }

    public SourceName getSourceName() {
        return sourceName;
    }

    public void setSourceName(SourceName value) {
        this.sourceName = ((SourceNameImpl) value);
    }

    public SourceDate getSourceDate() {
        return sourceDate;
    }

    public void setSourceDate(SourceDate value) {
        this.sourceDate = ((SourceDateImpl) value);
    }

}
