//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.Subtitle;
import org.springframework.social.orcid.jaxb.beans.TranslatedTitle;
import org.springframework.social.orcid.jaxb.beans.WorkTitle;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "subtitle",
    "translatedTitle"
})
@XmlRootElement(name = "work-title")
public class WorkTitleImpl
    implements WorkTitle
{

    @XmlElement(required = true)
    protected String title;
    @XmlElement(type = SubtitleImpl.class)
    protected SubtitleImpl subtitle;
    @XmlElement(name = "translated-title", type = TranslatedTitleImpl.class)
    protected TranslatedTitleImpl translatedTitle;

    public String getTitle() {
        return title;
    }

    public void setTitle(String value) {
        this.title = value;
    }

    public Subtitle getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(Subtitle value) {
        this.subtitle = ((SubtitleImpl) value);
    }

    public TranslatedTitle getTranslatedTitle() {
        return translatedTitle;
    }

    public void setTranslatedTitle(TranslatedTitle value) {
        this.translatedTitle = ((TranslatedTitleImpl) value);
    }

}
