//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.Scope;
import org.springframework.social.orcid.jaxb.beans.WorkExternalIdentifier;
import org.springframework.social.orcid.jaxb.beans.WorkExternalIdentifiers;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "workExternalIdentifiers"
})
@XmlRootElement(name = "work-external-identifiers")
public class WorkExternalIdentifiersImpl
    implements WorkExternalIdentifiers
{

    @XmlElement(name = "work-external-identifier", type = WorkExternalIdentifierImpl.class)
    protected List<WorkExternalIdentifier> workExternalIdentifiers;
    @XmlAttribute(name = "scope")
    protected Scope scope;

    public List<WorkExternalIdentifier> getWorkExternalIdentifiers() {
        if (workExternalIdentifiers == null) {
            workExternalIdentifiers = new ArrayList<WorkExternalIdentifier>();
        }
        return this.workExternalIdentifiers;
    }

    public Scope getScope() {
        return scope;
    }

    public void setScope(Scope value) {
        this.scope = value;
    }

}
