//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.ApplicationName;
import org.springframework.social.orcid.jaxb.beans.ApplicationSummary;
import org.springframework.social.orcid.jaxb.beans.ApplicationWebsite;
import org.springframework.social.orcid.jaxb.beans.ApprovalDate;
import org.springframework.social.orcid.jaxb.beans.OrcidId;
import org.springframework.social.orcid.jaxb.beans.ScopePaths;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationOrcid",
    "applicationName",
    "applicationWebsite",
    "approvalDate",
    "scopePaths",
    "applicationGroupOrcid",
    "applicationGroupName"
})
@XmlRootElement(name = "application-summary")
public class ApplicationSummaryImpl
    implements ApplicationSummary
{

    @XmlElement(name = "application-orcid", required = true, type = OrcidIdImpl.class)
    protected OrcidIdImpl applicationOrcid;
    @XmlElement(name = "application-name", required = true, type = ApplicationNameImpl.class)
    protected ApplicationNameImpl applicationName;
    @XmlElement(name = "application-website", required = true, type = ApplicationWebsiteImpl.class)
    protected ApplicationWebsiteImpl applicationWebsite;
    @XmlElement(name = "approval-date", required = true, type = ApprovalDateImpl.class)
    protected ApprovalDateImpl approvalDate;
    @XmlElement(name = "scope-paths", required = true, type = ScopePathsImpl.class)
    protected ScopePathsImpl scopePaths;
    @XmlElement(name = "application-group-orcid", required = true, type = OrcidIdImpl.class)
    protected OrcidIdImpl applicationGroupOrcid;
    @XmlElement(name = "application-group-name", required = true)
    protected String applicationGroupName;

    public OrcidId getApplicationOrcid() {
        return applicationOrcid;
    }

    public void setApplicationOrcid(OrcidId value) {
        this.applicationOrcid = ((OrcidIdImpl) value);
    }

    public ApplicationName getApplicationName() {
        return applicationName;
    }

    public void setApplicationName(ApplicationName value) {
        this.applicationName = ((ApplicationNameImpl) value);
    }

    public ApplicationWebsite getApplicationWebsite() {
        return applicationWebsite;
    }

    public void setApplicationWebsite(ApplicationWebsite value) {
        this.applicationWebsite = ((ApplicationWebsiteImpl) value);
    }

    public ApprovalDate getApprovalDate() {
        return approvalDate;
    }

    public void setApprovalDate(ApprovalDate value) {
        this.approvalDate = ((ApprovalDateImpl) value);
    }

    public ScopePaths getScopePaths() {
        return scopePaths;
    }

    public void setScopePaths(ScopePaths value) {
        this.scopePaths = ((ScopePathsImpl) value);
    }

    public OrcidId getApplicationGroupOrcid() {
        return applicationGroupOrcid;
    }

    public void setApplicationGroupOrcid(OrcidId value) {
        this.applicationGroupOrcid = ((OrcidIdImpl) value);
    }

    public String getApplicationGroupName() {
        return applicationGroupName;
    }

    public void setApplicationGroupName(String value) {
        this.applicationGroupName = value;
    }

}
