//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.DisambiguatedOrganization;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "disambiguated-organization", propOrder = {
    "disambiguatedOrganizationIdentifier",
    "disambiguationSource"
})
public class DisambiguatedOrganizationImpl
    implements DisambiguatedOrganization
{

    @XmlElement(name = "disambiguated-organization-identifier", required = true)
    protected String disambiguatedOrganizationIdentifier;
    @XmlElement(name = "disambiguation-source", required = true)
    protected String disambiguationSource;

    public String getDisambiguatedOrganizationIdentifier() {
        return disambiguatedOrganizationIdentifier;
    }

    public void setDisambiguatedOrganizationIdentifier(String value) {
        this.disambiguatedOrganizationIdentifier = value;
    }

    public String getDisambiguationSource() {
        return disambiguationSource;
    }

    public void setDisambiguationSource(String value) {
        this.disambiguationSource = value;
    }

}
