//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.ExternalIdCommonName;
import org.springframework.social.orcid.jaxb.beans.ExternalIdReference;
import org.springframework.social.orcid.jaxb.beans.ExternalIdUrl;
import org.springframework.social.orcid.jaxb.beans.ExternalIdentifier;
import org.springframework.social.orcid.jaxb.beans.Source;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "externalIdCommonName",
    "externalIdReference",
    "externalIdUrl",
    "source"
})
@XmlRootElement(name = "external-identifier")
public class ExternalIdentifierImpl
    implements ExternalIdentifier
{

    @XmlElement(name = "external-id-common-name", type = ExternalIdCommonNameImpl.class)
    protected ExternalIdCommonNameImpl externalIdCommonName;
    @XmlElement(name = "external-id-reference", type = ExternalIdReferenceImpl.class)
    protected ExternalIdReferenceImpl externalIdReference;
    @XmlElement(name = "external-id-url", type = ExternalIdUrlImpl.class)
    protected ExternalIdUrlImpl externalIdUrl;
    @XmlElement(type = SourceImpl.class)
    protected SourceImpl source;

    public ExternalIdCommonName getExternalIdCommonName() {
        return externalIdCommonName;
    }

    public void setExternalIdCommonName(ExternalIdCommonName value) {
        this.externalIdCommonName = ((ExternalIdCommonNameImpl) value);
    }

    public ExternalIdReference getExternalIdReference() {
        return externalIdReference;
    }

    public void setExternalIdReference(ExternalIdReference value) {
        this.externalIdReference = ((ExternalIdReferenceImpl) value);
    }

    public ExternalIdUrl getExternalIdUrl() {
        return externalIdUrl;
    }

    public void setExternalIdUrl(ExternalIdUrl value) {
        this.externalIdUrl = ((ExternalIdUrlImpl) value);
    }

    public Source getSource() {
        return source;
    }

    public void setSource(Source value) {
        this.source = ((SourceImpl) value);
    }

}
