//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.FundingContributorAttributes;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundingContributorRole"
})
@XmlRootElement(name = "funding-contributor-attributes")
public class FundingContributorAttributesImpl
    implements FundingContributorAttributes
{

    @XmlElement(name = "funding-contributor-role")
    protected String fundingContributorRole;

    public String getFundingContributorRole() {
        return fundingContributorRole;
    }

    public void setFundingContributorRole(String value) {
        this.fundingContributorRole = value;
    }

}
