//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.Amount;
import org.springframework.social.orcid.jaxb.beans.CreatedDate;
import org.springframework.social.orcid.jaxb.beans.Funding;
import org.springframework.social.orcid.jaxb.beans.FundingContributors;
import org.springframework.social.orcid.jaxb.beans.FundingExternalIdentifiers;
import org.springframework.social.orcid.jaxb.beans.FundingTitle;
import org.springframework.social.orcid.jaxb.beans.FuzzyDate;
import org.springframework.social.orcid.jaxb.beans.LastModifiedDate;
import org.springframework.social.orcid.jaxb.beans.Organization;
import org.springframework.social.orcid.jaxb.beans.Source;
import org.springframework.social.orcid.jaxb.beans.Url;
import org.springframework.social.orcid.jaxb.beans.Visibility;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundingType",
    "organizationDefinedType",
    "fundingTitle",
    "shortDescription",
    "amount",
    "url",
    "startDate",
    "endDate",
    "fundingExternalIdentifiers",
    "fundingContributors",
    "organization",
    "source",
    "createdDate",
    "lastModifiedDate"
})
@XmlRootElement(name = "funding")
public class FundingImpl
    implements Funding
{

    @XmlElement(name = "funding-type", required = true)
    protected String fundingType;
    @XmlElement(name = "organization-defined-type")
    protected String organizationDefinedType;
    @XmlElement(name = "funding-title", required = true, type = FundingTitleImpl.class)
    protected FundingTitleImpl fundingTitle;
    @XmlElement(name = "short-description")
    protected String shortDescription;
    @XmlElement(type = AmountImpl.class)
    protected AmountImpl amount;
    @XmlElement(type = UrlImpl.class)
    protected UrlImpl url;
    @XmlElement(name = "start-date", type = FuzzyDateImpl.class)
    protected FuzzyDateImpl startDate;
    @XmlElement(name = "end-date", type = FuzzyDateImpl.class)
    protected FuzzyDateImpl endDate;
    @XmlElement(name = "funding-external-identifiers", type = FundingExternalIdentifiersImpl.class)
    protected FundingExternalIdentifiersImpl fundingExternalIdentifiers;
    @XmlElement(name = "funding-contributors", type = FundingContributorsImpl.class)
    protected FundingContributorsImpl fundingContributors;
    @XmlElement(required = true, type = OrganizationImpl.class)
    protected OrganizationImpl organization;
    @XmlElement(type = SourceImpl.class)
    protected SourceImpl source;
    @XmlElement(name = "created-date", type = CreatedDateImpl.class)
    protected CreatedDateImpl createdDate;
    @XmlElement(name = "last-modified-date", type = LastModifiedDateImpl.class)
    protected LastModifiedDateImpl lastModifiedDate;
    @XmlAttribute(name = "put-code")
    protected BigInteger putCode;
    @XmlAttribute(name = "visibility")
    protected Visibility visibility;

    public String getFundingType() {
        return fundingType;
    }

    public void setFundingType(String value) {
        this.fundingType = value;
    }

    public String getOrganizationDefinedType() {
        return organizationDefinedType;
    }

    public void setOrganizationDefinedType(String value) {
        this.organizationDefinedType = value;
    }

    public FundingTitle getFundingTitle() {
        return fundingTitle;
    }

    public void setFundingTitle(FundingTitle value) {
        this.fundingTitle = ((FundingTitleImpl) value);
    }

    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    public Amount getAmount() {
        return amount;
    }

    public void setAmount(Amount value) {
        this.amount = ((AmountImpl) value);
    }

    public Url getUrl() {
        return url;
    }

    public void setUrl(Url value) {
        this.url = ((UrlImpl) value);
    }

    public FuzzyDate getStartDate() {
        return startDate;
    }

    public void setStartDate(FuzzyDate value) {
        this.startDate = ((FuzzyDateImpl) value);
    }

    public FuzzyDate getEndDate() {
        return endDate;
    }

    public void setEndDate(FuzzyDate value) {
        this.endDate = ((FuzzyDateImpl) value);
    }

    public FundingExternalIdentifiers getFundingExternalIdentifiers() {
        return fundingExternalIdentifiers;
    }

    public void setFundingExternalIdentifiers(FundingExternalIdentifiers value) {
        this.fundingExternalIdentifiers = ((FundingExternalIdentifiersImpl) value);
    }

    public FundingContributors getFundingContributors() {
        return fundingContributors;
    }

    public void setFundingContributors(FundingContributors value) {
        this.fundingContributors = ((FundingContributorsImpl) value);
    }

    public Organization getOrganization() {
        return organization;
    }

    public void setOrganization(Organization value) {
        this.organization = ((OrganizationImpl) value);
    }

    public Source getSource() {
        return source;
    }

    public void setSource(Source value) {
        this.source = ((SourceImpl) value);
    }

    public CreatedDate getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(CreatedDate value) {
        this.createdDate = ((CreatedDateImpl) value);
    }

    public LastModifiedDate getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(LastModifiedDate value) {
        this.lastModifiedDate = ((LastModifiedDateImpl) value);
    }

    public BigInteger getPutCode() {
        return putCode;
    }

    public void setPutCode(BigInteger value) {
        this.putCode = value;
    }

    public Visibility getVisibility() {
        return visibility;
    }

    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

}
