//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.FundingExternalIdentifier;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundingExternalIdentifierType",
    "fundingExternalIdentifierValue",
    "fundingExternalIdentifierUrl"
})
@XmlRootElement(name = "funding-external-identifier")
public class FundingExternalIdentifierImpl
    implements FundingExternalIdentifier
{

    @XmlElement(name = "funding-external-identifier-type", required = true)
    protected String fundingExternalIdentifierType;
    @XmlElement(name = "funding-external-identifier-value")
    protected String fundingExternalIdentifierValue;
    @XmlElement(name = "funding-external-identifier-url")
    @XmlSchemaType(name = "anyURI")
    protected String fundingExternalIdentifierUrl;

    public String getFundingExternalIdentifierType() {
        return fundingExternalIdentifierType;
    }

    public void setFundingExternalIdentifierType(String value) {
        this.fundingExternalIdentifierType = value;
    }

    public String getFundingExternalIdentifierValue() {
        return fundingExternalIdentifierValue;
    }

    public void setFundingExternalIdentifierValue(String value) {
        this.fundingExternalIdentifierValue = value;
    }

    public String getFundingExternalIdentifierUrl() {
        return fundingExternalIdentifierUrl;
    }

    public void setFundingExternalIdentifierUrl(String value) {
        this.fundingExternalIdentifierUrl = value;
    }

}
