//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.ErrorDesc;
import org.springframework.social.orcid.jaxb.beans.OrcidMessage;
import org.springframework.social.orcid.jaxb.beans.OrcidProfile;
import org.springframework.social.orcid.jaxb.beans.OrcidSearchResults;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageVersion",
    "errorDesc",
    "orcidSearchResults",
    "orcidProfile"
})
@XmlRootElement(name = "orcid-message")
public class OrcidMessageImpl
    implements OrcidMessage
{

    @XmlElement(name = "message-version", required = true)
    protected String messageVersion;
    @XmlElement(name = "error-desc", type = ErrorDescImpl.class)
    protected ErrorDescImpl errorDesc;
    @XmlElement(name = "orcid-search-results", type = OrcidSearchResultsImpl.class)
    protected OrcidSearchResultsImpl orcidSearchResults;
    @XmlElement(name = "orcid-profile", type = OrcidProfileImpl.class)
    protected OrcidProfileImpl orcidProfile;

    public String getMessageVersion() {
        return messageVersion;
    }

    public void setMessageVersion(String value) {
        this.messageVersion = value;
    }

    public ErrorDesc getErrorDesc() {
        return errorDesc;
    }

    public void setErrorDesc(ErrorDesc value) {
        this.errorDesc = ((ErrorDescImpl) value);
    }

    public OrcidSearchResults getOrcidSearchResults() {
        return orcidSearchResults;
    }

    public void setOrcidSearchResults(OrcidSearchResults value) {
        this.orcidSearchResults = ((OrcidSearchResultsImpl) value);
    }

    public OrcidProfile getOrcidProfile() {
        return orcidProfile;
    }

    public void setOrcidProfile(OrcidProfile value) {
        this.orcidProfile = ((OrcidProfileImpl) value);
    }

}
