//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.OrcidSearchResult;
import org.springframework.social.orcid.jaxb.beans.OrcidSearchResults;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orcidSearchResults"
})
@XmlRootElement(name = "orcid-search-results")
public class OrcidSearchResultsImpl
    implements OrcidSearchResults
{

    @XmlElement(name = "orcid-search-result", type = OrcidSearchResultImpl.class)
    protected List<OrcidSearchResult> orcidSearchResults;
    @XmlAttribute(name = "num-found")
    protected BigInteger numFound;

    public List<OrcidSearchResult> getOrcidSearchResults() {
        if (orcidSearchResults == null) {
            orcidSearchResults = new ArrayList<OrcidSearchResult>();
        }
        return this.orcidSearchResults;
    }

    public BigInteger getNumFound() {
        if (numFound == null) {
            return new BigInteger("0");
        } else {
            return numFound;
        }
    }

    public void setNumFound(BigInteger value) {
        this.numFound = value;
    }

}
