//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.Affiliations;
import org.springframework.social.orcid.jaxb.beans.FundingList;
import org.springframework.social.orcid.jaxb.beans.OrcidActivities;
import org.springframework.social.orcid.jaxb.beans.OrcidWorks;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "affiliations",
    "orcidWorks",
    "fundingList"
})
@XmlRootElement(name = "orcid-activities")
public class OrcidActivitiesImpl
    implements OrcidActivities
{

    @XmlElement(type = AffiliationsImpl.class)
    protected AffiliationsImpl affiliations;
    @XmlElement(name = "orcid-works", type = OrcidWorksImpl.class)
    protected OrcidWorksImpl orcidWorks;
    @XmlElement(name = "funding-list", type = FundingListImpl.class)
    protected FundingListImpl fundingList;

    public Affiliations getAffiliations() {
        return affiliations;
    }

    public void setAffiliations(Affiliations value) {
        this.affiliations = ((AffiliationsImpl) value);
    }

    public OrcidWorks getOrcidWorks() {
        return orcidWorks;
    }

    public void setOrcidWorks(OrcidWorks value) {
        this.orcidWorks = ((OrcidWorksImpl) value);
    }

    public FundingList getFundingList() {
        return fundingList;
    }

    public void setFundingList(FundingList value) {
        this.fundingList = ((FundingListImpl) value);
    }

}
