//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.OrcidProfile;
import org.springframework.social.orcid.jaxb.beans.OrcidSearchResult;
import org.springframework.social.orcid.jaxb.beans.RelevancyScore;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "relevancyScore",
    "orcidProfile"
})
@XmlRootElement(name = "orcid-search-result")
public class OrcidSearchResultImpl
    implements OrcidSearchResult
{

    @XmlElement(name = "relevancy-score", required = true, type = RelevancyScoreImpl.class)
    protected RelevancyScoreImpl relevancyScore;
    @XmlElement(name = "orcid-profile", required = true, type = OrcidProfileImpl.class)
    protected OrcidProfileImpl orcidProfile;

    public RelevancyScore getRelevancyScore() {
        return relevancyScore;
    }

    public void setRelevancyScore(RelevancyScore value) {
        this.relevancyScore = ((RelevancyScoreImpl) value);
    }

    public OrcidProfile getOrcidProfile() {
        return orcidProfile;
    }

    public void setOrcidProfile(OrcidProfile value) {
        this.orcidProfile = ((OrcidProfileImpl) value);
    }

}
