//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.OrcidId;
import org.springframework.social.orcid.jaxb.beans.OrcidInternal;
import org.springframework.social.orcid.jaxb.beans.Preferences;
import org.springframework.social.orcid.jaxb.beans.Scope;
import org.springframework.social.orcid.jaxb.beans.SecurityDetails;
import org.springframework.social.orcid.jaxb.beans.Visibility;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "securityDetails",
    "preferences",
    "groupOrcidIdentifier",
    "referredBy",
    "salesforceId"
})
@XmlRootElement(name = "orcid-internal")
public class OrcidInternalImpl
    implements OrcidInternal
{

    @XmlElement(name = "security-details", type = SecurityDetailsImpl.class)
    protected SecurityDetailsImpl securityDetails;
    @XmlElement(type = PreferencesImpl.class)
    protected PreferencesImpl preferences;
    @XmlElement(name = "group-orcid-identifier", type = OrcidIdImpl.class)
    protected OrcidIdImpl groupOrcidIdentifier;
    @XmlElement(name = "referred-by")
    protected String referredBy;
    @XmlElement(name = "salesforce-id")
    protected String salesforceId;
    @XmlAttribute(name = "visibility")
    protected Visibility visibility;
    @XmlAttribute(name = "scope")
    protected Scope scope;

    public SecurityDetails getSecurityDetails() {
        return securityDetails;
    }

    public void setSecurityDetails(SecurityDetails value) {
        this.securityDetails = ((SecurityDetailsImpl) value);
    }

    public Preferences getPreferences() {
        return preferences;
    }

    public void setPreferences(Preferences value) {
        this.preferences = ((PreferencesImpl) value);
    }

    public OrcidId getGroupOrcidIdentifier() {
        return groupOrcidIdentifier;
    }

    public void setGroupOrcidIdentifier(OrcidId value) {
        this.groupOrcidIdentifier = ((OrcidIdImpl) value);
    }

    public String getReferredBy() {
        return referredBy;
    }

    public void setReferredBy(String value) {
        this.referredBy = value;
    }

    public String getSalesforceId() {
        return salesforceId;
    }

    public void setSalesforceId(String value) {
        this.salesforceId = value;
    }

    public Visibility getVisibility() {
        return visibility;
    }

    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

    public Scope getScope() {
        return scope;
    }

    public void setScope(Scope value) {
        this.scope = value;
    }

}
