//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.Country;
import org.springframework.social.orcid.jaxb.beans.CreatedDate;
import org.springframework.social.orcid.jaxb.beans.JournalTitle;
import org.springframework.social.orcid.jaxb.beans.LanguageCode;
import org.springframework.social.orcid.jaxb.beans.LastModifiedDate;
import org.springframework.social.orcid.jaxb.beans.OrcidWork;
import org.springframework.social.orcid.jaxb.beans.PublicationDate;
import org.springframework.social.orcid.jaxb.beans.Source;
import org.springframework.social.orcid.jaxb.beans.Url;
import org.springframework.social.orcid.jaxb.beans.Visibility;
import org.springframework.social.orcid.jaxb.beans.WorkCitation;
import org.springframework.social.orcid.jaxb.beans.WorkContributors;
import org.springframework.social.orcid.jaxb.beans.WorkExternalIdentifiers;
import org.springframework.social.orcid.jaxb.beans.WorkTitle;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "workTitle",
    "journalTitle",
    "shortDescription",
    "workCitation",
    "workType",
    "publicationDate",
    "workExternalIdentifiers",
    "url",
    "workContributors",
    "source",
    "createdDate",
    "lastModifiedDate",
    "languageCode",
    "country"
})
@XmlRootElement(name = "orcid-work")
public class OrcidWorkImpl
    implements OrcidWork
{

    @XmlElement(name = "work-title", type = WorkTitleImpl.class)
    protected WorkTitleImpl workTitle;
    @XmlElement(name = "journal-title", type = JournalTitleImpl.class)
    protected JournalTitleImpl journalTitle;
    @XmlElement(name = "short-description")
    protected String shortDescription;
    @XmlElement(name = "work-citation", type = WorkCitationImpl.class)
    protected WorkCitationImpl workCitation;
    @XmlElement(name = "work-type", required = true)
    protected String workType;
    @XmlElement(name = "publication-date", type = PublicationDateImpl.class)
    protected PublicationDateImpl publicationDate;
    @XmlElement(name = "work-external-identifiers", type = WorkExternalIdentifiersImpl.class)
    protected WorkExternalIdentifiersImpl workExternalIdentifiers;
    @XmlElement(type = UrlImpl.class)
    protected UrlImpl url;
    @XmlElement(name = "work-contributors", type = WorkContributorsImpl.class)
    protected WorkContributorsImpl workContributors;
    @XmlElement(type = SourceImpl.class)
    protected SourceImpl source;
    @XmlElement(name = "created-date", type = CreatedDateImpl.class)
    protected CreatedDateImpl createdDate;
    @XmlElement(name = "last-modified-date", type = LastModifiedDateImpl.class)
    protected LastModifiedDateImpl lastModifiedDate;
    @XmlElement(name = "language-code")
    @XmlSchemaType(name = "string")
    protected LanguageCode languageCode;
    @XmlElement(type = CountryImpl.class)
    protected CountryImpl country;
    @XmlAttribute(name = "visibility")
    protected Visibility visibility;
    @XmlAttribute(name = "put-code")
    protected BigInteger putCode;

    public WorkTitle getWorkTitle() {
        return workTitle;
    }

    public void setWorkTitle(WorkTitle value) {
        this.workTitle = ((WorkTitleImpl) value);
    }

    public JournalTitle getJournalTitle() {
        return journalTitle;
    }

    public void setJournalTitle(JournalTitle value) {
        this.journalTitle = ((JournalTitleImpl) value);
    }

    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    public WorkCitation getWorkCitation() {
        return workCitation;
    }

    public void setWorkCitation(WorkCitation value) {
        this.workCitation = ((WorkCitationImpl) value);
    }

    public String getWorkType() {
        return workType;
    }

    public void setWorkType(String value) {
        this.workType = value;
    }

    public PublicationDate getPublicationDate() {
        return publicationDate;
    }

    public void setPublicationDate(PublicationDate value) {
        this.publicationDate = ((PublicationDateImpl) value);
    }

    public WorkExternalIdentifiers getWorkExternalIdentifiers() {
        return workExternalIdentifiers;
    }

    public void setWorkExternalIdentifiers(WorkExternalIdentifiers value) {
        this.workExternalIdentifiers = ((WorkExternalIdentifiersImpl) value);
    }

    public Url getUrl() {
        return url;
    }

    public void setUrl(Url value) {
        this.url = ((UrlImpl) value);
    }

    public WorkContributors getWorkContributors() {
        return workContributors;
    }

    public void setWorkContributors(WorkContributors value) {
        this.workContributors = ((WorkContributorsImpl) value);
    }

    public Source getSource() {
        return source;
    }

    public void setSource(Source value) {
        this.source = ((SourceImpl) value);
    }

    public CreatedDate getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(CreatedDate value) {
        this.createdDate = ((CreatedDateImpl) value);
    }

    public LastModifiedDate getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(LastModifiedDate value) {
        this.lastModifiedDate = ((LastModifiedDateImpl) value);
    }

    public LanguageCode getLanguageCode() {
        return languageCode;
    }

    public void setLanguageCode(LanguageCode value) {
        this.languageCode = value;
    }

    public Country getCountry() {
        return country;
    }

    public void setCountry(Country value) {
        this.country = ((CountryImpl) value);
    }

    public Visibility getVisibility() {
        return visibility;
    }

    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

    public BigInteger getPutCode() {
        return putCode;
    }

    public void setPutCode(BigInteger value) {
        this.putCode = value;
    }

}
