//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.ClientType;
import org.springframework.social.orcid.jaxb.beans.GroupType;
import org.springframework.social.orcid.jaxb.beans.OrcidActivities;
import org.springframework.social.orcid.jaxb.beans.OrcidBio;
import org.springframework.social.orcid.jaxb.beans.OrcidDeprecated;
import org.springframework.social.orcid.jaxb.beans.OrcidHistory;
import org.springframework.social.orcid.jaxb.beans.OrcidId;
import org.springframework.social.orcid.jaxb.beans.OrcidInternal;
import org.springframework.social.orcid.jaxb.beans.OrcidPreferences;
import org.springframework.social.orcid.jaxb.beans.OrcidProfile;
import org.springframework.social.orcid.jaxb.beans.OrcidType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orcidIdentifier",
    "orcidDeprecated",
    "orcidPreferences",
    "orcidHistory",
    "orcidBio",
    "orcidActivities",
    "orcidInternal"
})
@XmlRootElement(name = "orcid-profile")
public class OrcidProfileImpl
    implements OrcidProfile
{

    @XmlElement(name = "orcid-identifier", type = OrcidIdImpl.class)
    protected OrcidIdImpl orcidIdentifier;
    @XmlElement(name = "orcid-deprecated", type = OrcidDeprecatedImpl.class)
    protected OrcidDeprecatedImpl orcidDeprecated;
    @XmlElement(name = "orcid-preferences", type = OrcidPreferencesImpl.class)
    protected OrcidPreferencesImpl orcidPreferences;
    @XmlElement(name = "orcid-history", type = OrcidHistoryImpl.class)
    protected OrcidHistoryImpl orcidHistory;
    @XmlElement(name = "orcid-bio", type = OrcidBioImpl.class)
    protected OrcidBioImpl orcidBio;
    @XmlElement(name = "orcid-activities", type = OrcidActivitiesImpl.class)
    protected OrcidActivitiesImpl orcidActivities;
    @XmlElement(name = "orcid-internal", type = OrcidInternalImpl.class)
    protected OrcidInternalImpl orcidInternal;
    @XmlAttribute(name = "type")
    protected OrcidType type;
    @XmlAttribute(name = "client-type")
    protected ClientType clientType;
    @XmlAttribute(name = "group-type")
    protected GroupType groupType;

    public OrcidId getOrcidIdentifier() {
        return orcidIdentifier;
    }

    public void setOrcidIdentifier(OrcidId value) {
        this.orcidIdentifier = ((OrcidIdImpl) value);
    }

    public OrcidDeprecated getOrcidDeprecated() {
        return orcidDeprecated;
    }

    public void setOrcidDeprecated(OrcidDeprecated value) {
        this.orcidDeprecated = ((OrcidDeprecatedImpl) value);
    }

    public OrcidPreferences getOrcidPreferences() {
        return orcidPreferences;
    }

    public void setOrcidPreferences(OrcidPreferences value) {
        this.orcidPreferences = ((OrcidPreferencesImpl) value);
    }

    public OrcidHistory getOrcidHistory() {
        return orcidHistory;
    }

    public void setOrcidHistory(OrcidHistory value) {
        this.orcidHistory = ((OrcidHistoryImpl) value);
    }

    public OrcidBio getOrcidBio() {
        return orcidBio;
    }

    public void setOrcidBio(OrcidBio value) {
        this.orcidBio = ((OrcidBioImpl) value);
    }

    public OrcidActivities getOrcidActivities() {
        return orcidActivities;
    }

    public void setOrcidActivities(OrcidActivities value) {
        this.orcidActivities = ((OrcidActivitiesImpl) value);
    }

    public OrcidInternal getOrcidInternal() {
        return orcidInternal;
    }

    public void setOrcidInternal(OrcidInternal value) {
        this.orcidInternal = ((OrcidInternalImpl) value);
    }

    public OrcidType getType() {
        if (type == null) {
            return OrcidType.USER;
        } else {
            return type;
        }
    }

    public void setType(OrcidType value) {
        this.type = value;
    }

    public ClientType getClientType() {
        return clientType;
    }

    public void setClientType(ClientType value) {
        this.clientType = value;
    }

    public GroupType getGroupType() {
        return groupType;
    }

    public void setGroupType(GroupType value) {
        this.groupType = value;
    }

}
