//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.ActivitiesVisibilityDefault;
import org.springframework.social.orcid.jaxb.beans.DeveloperToolsEnabled;
import org.springframework.social.orcid.jaxb.beans.Preferences;
import org.springframework.social.orcid.jaxb.beans.SendChangeNotifications;
import org.springframework.social.orcid.jaxb.beans.SendOrcidNews;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendEmailFrequencyDays",
    "sendChangeNotifications",
    "sendOrcidNews",
    "sendMemberUpdateRequests",
    "activitiesVisibilityDefault",
    "developerToolsEnabled"
})
@XmlRootElement(name = "preferences")
public class PreferencesImpl
    implements Preferences
{

    @XmlElement(name = "send-email-frequency-days", required = true)
    protected String sendEmailFrequencyDays;
    @XmlElement(name = "send-change-notifications", required = true, type = SendChangeNotificationsImpl.class)
    protected SendChangeNotificationsImpl sendChangeNotifications;
    @XmlElement(name = "send-orcid-news", required = true, type = SendOrcidNewsImpl.class)
    protected SendOrcidNewsImpl sendOrcidNews;
    @XmlElement(name = "send-member-update-requests")
    protected boolean sendMemberUpdateRequests;
    @XmlElement(name = "activities-visibility-default", required = true, type = ActivitiesVisibilityDefaultImpl.class)
    protected ActivitiesVisibilityDefaultImpl activitiesVisibilityDefault;
    @XmlElement(name = "developer-tools-enabled", type = DeveloperToolsEnabledImpl.class)
    protected DeveloperToolsEnabledImpl developerToolsEnabled;

    public String getSendEmailFrequencyDays() {
        return sendEmailFrequencyDays;
    }

    public void setSendEmailFrequencyDays(String value) {
        this.sendEmailFrequencyDays = value;
    }

    public SendChangeNotifications getSendChangeNotifications() {
        return sendChangeNotifications;
    }

    public void setSendChangeNotifications(SendChangeNotifications value) {
        this.sendChangeNotifications = ((SendChangeNotificationsImpl) value);
    }

    public SendOrcidNews getSendOrcidNews() {
        return sendOrcidNews;
    }

    public void setSendOrcidNews(SendOrcidNews value) {
        this.sendOrcidNews = ((SendOrcidNewsImpl) value);
    }

    public boolean isSendMemberUpdateRequests() {
        return sendMemberUpdateRequests;
    }

    public void setSendMemberUpdateRequests(boolean value) {
        this.sendMemberUpdateRequests = value;
    }

    public ActivitiesVisibilityDefault getActivitiesVisibilityDefault() {
        return activitiesVisibilityDefault;
    }

    public void setActivitiesVisibilityDefault(ActivitiesVisibilityDefault value) {
        this.activitiesVisibilityDefault = ((ActivitiesVisibilityDefaultImpl) value);
    }

    public DeveloperToolsEnabled getDeveloperToolsEnabled() {
        return developerToolsEnabled;
    }

    public void setDeveloperToolsEnabled(DeveloperToolsEnabled value) {
        this.developerToolsEnabled = ((DeveloperToolsEnabledImpl) value);
    }

}
