//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.ResearcherUrl;
import org.springframework.social.orcid.jaxb.beans.Url;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "urlName",
    "url"
})
@XmlRootElement(name = "researcher-url")
public class ResearcherUrlImpl
    implements ResearcherUrl
{

    @XmlElement(name = "url-name")
    protected String urlName;
    @XmlElement(type = UrlImpl.class)
    protected UrlImpl url;

    public String getUrlName() {
        return urlName;
    }

    public void setUrlName(String value) {
        this.urlName = value;
    }

    public Url getUrl() {
        return url;
    }

    public void setUrl(Url value) {
        this.url = ((UrlImpl) value);
    }

}
