//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.springframework.social.orcid.jaxb.beans.CitationType;
import org.springframework.social.orcid.jaxb.beans.WorkCitation;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "citation", propOrder = {
    "workCitationType",
    "citation"
})
@XmlRootElement(name = "work-citation")
public class WorkCitationImpl
    implements WorkCitation
{

    @XmlElement(name = "work-citation-type", required = true, defaultValue = "formatted-unspecified")
    @XmlSchemaType(name = "string")
    protected CitationType workCitationType;
    @XmlElement(required = true)
    protected String citation;

    public CitationType getWorkCitationType() {
        return workCitationType;
    }

    public void setWorkCitationType(CitationType value) {
        this.workCitationType = value;
    }

    public String getCitation() {
        return citation;
    }

    public void setCitation(String value) {
        this.citation = value;
    }

}
