//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}application-orcid"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}application-name"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}application-website"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}approval-date"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}scope-paths"/>
 *         &lt;element name="application-group-orcid" type="{http://www.orcid.org/ns/orcid}orcid-id"/>
 *         &lt;element name="application-group-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface ApplicationSummary {


    /**
     * Gets the value of the applicationOrcid property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidId }
     *     
     */
    OrcidId getApplicationOrcid();

    /**
     * Sets the value of the applicationOrcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidId }
     *     
     */
    void setApplicationOrcid(OrcidId value);

    /**
     * Gets the value of the applicationName property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationName }
     *     
     */
    ApplicationName getApplicationName();

    /**
     * Sets the value of the applicationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationName }
     *     
     */
    void setApplicationName(ApplicationName value);

    /**
     * Gets the value of the applicationWebsite property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationWebsite }
     *     
     */
    ApplicationWebsite getApplicationWebsite();

    /**
     * Sets the value of the applicationWebsite property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationWebsite }
     *     
     */
    void setApplicationWebsite(ApplicationWebsite value);

    /**
     * Gets the value of the approvalDate property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalDate }
     *     
     */
    ApprovalDate getApprovalDate();

    /**
     * Sets the value of the approvalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalDate }
     *     
     */
    void setApprovalDate(ApprovalDate value);

    /**
     * Gets the value of the scopePaths property.
     * 
     * @return
     *     possible object is
     *     {@link ScopePaths }
     *     
     */
    ScopePaths getScopePaths();

    /**
     * Sets the value of the scopePaths property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScopePaths }
     *     
     */
    void setScopePaths(ScopePaths value);

    /**
     * Gets the value of the applicationGroupOrcid property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidId }
     *     
     */
    OrcidId getApplicationGroupOrcid();

    /**
     * Sets the value of the applicationGroupOrcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidId }
     *     
     */
    void setApplicationGroupOrcid(OrcidId value);

    /**
     * Gets the value of the applicationGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getApplicationGroupName();

    /**
     * Sets the value of the applicationGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setApplicationGroupName(String value);

}
