//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import org.springframework.social.orcid.jaxb.beans.impl.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.hr.orcid.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static Void _useJAXBProperties = null;
    private final static QName _SourceOrcid_QNAME = new QName("http://www.orcid.org/ns/orcid", "source-orcid");
    private final static QName _SendEmailFrequencyDays_QNAME = new QName("http://www.orcid.org/ns/orcid", "send-email-frequency-days");
    private final static QName _ShortDescription_QNAME = new QName("http://www.orcid.org/ns/orcid", "short-description");
    private final static QName _OrcidIdentifier_QNAME = new QName("http://www.orcid.org/ns/orcid", "orcid-identifier");
    private final static QName _Locale_QNAME = new QName("http://www.orcid.org/ns/orcid", "locale");
    private final static QName _WorkExternalIdentifierType_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-external-identifier-type");
    private final static QName _WorkType_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-type");
    private final static QName _FundingExternalIdentifierType_QNAME = new QName("http://www.orcid.org/ns/orcid", "funding-external-identifier-type");
    private final static QName _MessageVersion_QNAME = new QName("http://www.orcid.org/ns/orcid", "message-version");
    private final static QName _FundingContributorRole_QNAME = new QName("http://www.orcid.org/ns/orcid", "funding-contributor-role");
    private final static QName _ApplicationOrcid_QNAME = new QName("http://www.orcid.org/ns/orcid", "application-orcid");
    private final static QName _SendMemberUpdateRequests_QNAME = new QName("http://www.orcid.org/ns/orcid", "send-member-update-requests");
    private final static QName _DisambiguatedOrganizationIdentifier_QNAME = new QName("http://www.orcid.org/ns/orcid", "disambiguated-organization-identifier");
    private final static QName _OrganizationDefinedType_QNAME = new QName("http://www.orcid.org/ns/orcid", "organization-defined-type");
    private final static QName _FundingType_QNAME = new QName("http://www.orcid.org/ns/orcid", "funding-type");
    private final static QName _SalesforceId_QNAME = new QName("http://www.orcid.org/ns/orcid", "salesforce-id");
    private final static QName _ContributorSequence_QNAME = new QName("http://www.orcid.org/ns/orcid", "contributor-sequence");
    private final static QName _DisambiguationSource_QNAME = new QName("http://www.orcid.org/ns/orcid", "disambiguation-source");
    private final static QName _ContributorOrcid_QNAME = new QName("http://www.orcid.org/ns/orcid", "contributor-orcid");
    private final static QName _Host_QNAME = new QName("http://www.orcid.org/ns/orcid", "host");
    private final static QName _Path_QNAME = new QName("http://www.orcid.org/ns/orcid", "path");
    private final static QName _WorkExternalIdentifierId_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-external-identifier-id");
    private final static QName _ContributorRole_QNAME = new QName("http://www.orcid.org/ns/orcid", "contributor-role");
    private final static QName _WorkSource_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-source");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.hr.orcid.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SecurityDetails }
     * 
     */
    public SecurityDetails createSecurityDetails() {
        return new SecurityDetailsImpl();
    }

    /**
     * Create an instance of {@link EncryptedPassword }
     * 
     */
    public EncryptedPassword createEncryptedPassword() {
        return new EncryptedPasswordImpl();
    }

    /**
     * Create an instance of {@link SecurityQuestionId }
     * 
     */
    public SecurityQuestionId createSecurityQuestionId() {
        return new SecurityQuestionIdImpl();
    }

    /**
     * Create an instance of {@link EncryptedSecurityAnswer }
     * 
     */
    public EncryptedSecurityAnswer createEncryptedSecurityAnswer() {
        return new EncryptedSecurityAnswerImpl();
    }

    /**
     * Create an instance of {@link EncryptedVerificationCode }
     * 
     */
    public EncryptedVerificationCode createEncryptedVerificationCode() {
        return new EncryptedVerificationCodeImpl();
    }

    /**
     * Create an instance of {@link FundingContributorAttributes }
     * 
     */
    public FundingContributorAttributes createFundingContributorAttributes() {
        return new FundingContributorAttributesImpl();
    }

    /**
     * Create an instance of {@link Year }
     * 
     */
    public Year createYear() {
        return new YearImpl();
    }

    /**
     * Create an instance of {@link OrcidDeprecated }
     * 
     */
    public OrcidDeprecated createOrcidDeprecated() {
        return new OrcidDeprecatedImpl();
    }

    /**
     * Create an instance of {@link DeprecatedDate }
     * 
     */
    public DeprecatedDate createDeprecatedDate() {
        return new DeprecatedDateImpl();
    }

    /**
     * Create an instance of {@link PrimaryRecord }
     * 
     */
    public PrimaryRecord createPrimaryRecord() {
        return new PrimaryRecordImpl();
    }

    /**
     * Create an instance of {@link OrcidId }
     * 
     */
    public OrcidId createOrcidId() {
        return new OrcidIdImpl();
    }

    /**
     * Create an instance of {@link Claimed }
     * 
     */
    public Claimed createClaimed() {
        return new ClaimedImpl();
    }

    /**
     * Create an instance of {@link SourceReference }
     * 
     */
    public SourceReference createSourceReference() {
        return new SourceReferenceImpl();
    }

    /**
     * Create an instance of {@link SourceDate }
     * 
     */
    public SourceDate createSourceDate() {
        return new SourceDateImpl();
    }

    /**
     * Create an instance of {@link WorkExternalIdentifiers }
     * 
     */
    public WorkExternalIdentifiers createWorkExternalIdentifiers() {
        return new WorkExternalIdentifiersImpl();
    }

    /**
     * Create an instance of {@link WorkExternalIdentifier }
     * 
     */
    public WorkExternalIdentifier createWorkExternalIdentifier() {
        return new WorkExternalIdentifierImpl();
    }

    /**
     * Create an instance of {@link FundingContributors }
     * 
     */
    public FundingContributors createFundingContributors() {
        return new FundingContributorsImpl();
    }

    /**
     * Create an instance of {@link FundingContributor }
     * 
     */
    public FundingContributor createFundingContributor() {
        return new FundingContributorImpl();
    }

    /**
     * Create an instance of {@link CreditName }
     * 
     */
    public CreditName createCreditName() {
        return new CreditNameImpl();
    }

    /**
     * Create an instance of {@link ContributorEmail }
     * 
     */
    public ContributorEmail createContributorEmail() {
        return new ContributorEmailImpl();
    }

    /**
     * Create an instance of {@link OrcidWorks }
     * 
     */
    public OrcidWorks createOrcidWorks() {
        return new OrcidWorksImpl();
    }

    /**
     * Create an instance of {@link OrcidWork }
     * 
     */
    public OrcidWork createOrcidWork() {
        return new OrcidWorkImpl();
    }

    /**
     * Create an instance of {@link WorkTitle }
     * 
     */
    public WorkTitle createWorkTitle() {
        return new WorkTitleImpl();
    }

    /**
     * Create an instance of {@link Subtitle }
     * 
     */
    public Subtitle createSubtitle() {
        return new SubtitleImpl();
    }

    /**
     * Create an instance of {@link TranslatedTitle }
     * 
     */
    public TranslatedTitle createTranslatedTitle() {
        return new TranslatedTitleImpl();
    }

    /**
     * Create an instance of {@link StringWithLangCode }
     * 
     */
    public StringWithLangCode createStringWithLangCode() {
        return new StringWithLangCodeImpl();
    }

    /**
     * Create an instance of {@link JournalTitle }
     * 
     */
    public JournalTitle createJournalTitle() {
        return new JournalTitleImpl();
    }

    /**
     * Create an instance of {@link WorkCitation }
     * 
     */
    public WorkCitation createWorkCitation() {
        return new WorkCitationImpl();
    }

    /**
     * Create an instance of {@link PublicationDate }
     * 
     */
    public PublicationDate createPublicationDate() {
        return new PublicationDateImpl();
    }

    /**
     * Create an instance of {@link FuzzyDate }
     * 
     */
    public FuzzyDate createFuzzyDate() {
        return new FuzzyDateImpl();
    }

    /**
     * Create an instance of {@link Month }
     * 
     */
    public Month createMonth() {
        return new MonthImpl();
    }

    /**
     * Create an instance of {@link Day }
     * 
     */
    public Day createDay() {
        return new DayImpl();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new UrlImpl();
    }

    /**
     * Create an instance of {@link WorkContributors }
     * 
     */
    public WorkContributors createWorkContributors() {
        return new WorkContributorsImpl();
    }

    /**
     * Create an instance of {@link Contributor }
     * 
     */
    public Contributor createContributor() {
        return new ContributorImpl();
    }

    /**
     * Create an instance of {@link ContributorAttributes }
     * 
     */
    public ContributorAttributes createContributorAttributes() {
        return new ContributorAttributesImpl();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new SourceImpl();
    }

    /**
     * Create an instance of {@link SourceClientId }
     * 
     */
    public SourceClientId createSourceClientId() {
        return new SourceClientIdImpl();
    }

    /**
     * Create an instance of {@link SourceName }
     * 
     */
    public SourceName createSourceName() {
        return new SourceNameImpl();
    }

    /**
     * Create an instance of {@link CreatedDate }
     * 
     */
    public CreatedDate createCreatedDate() {
        return new CreatedDateImpl();
    }

    /**
     * Create an instance of {@link LastModifiedDate }
     * 
     */
    public LastModifiedDate createLastModifiedDate() {
        return new LastModifiedDateImpl();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new CountryImpl();
    }

    /**
     * Create an instance of {@link ApplicationSummary }
     * 
     */
    public ApplicationSummary createApplicationSummary() {
        return new ApplicationSummaryImpl();
    }

    /**
     * Create an instance of {@link ApplicationName }
     * 
     */
    public ApplicationName createApplicationName() {
        return new ApplicationNameImpl();
    }

    /**
     * Create an instance of {@link ApplicationWebsite }
     * 
     */
    public ApplicationWebsite createApplicationWebsite() {
        return new ApplicationWebsiteImpl();
    }

    /**
     * Create an instance of {@link ApprovalDate }
     * 
     */
    public ApprovalDate createApprovalDate() {
        return new ApprovalDateImpl();
    }

    /**
     * Create an instance of {@link ScopePaths }
     * 
     */
    public ScopePaths createScopePaths() {
        return new ScopePathsImpl();
    }

    /**
     * Create an instance of {@link ScopePath }
     * 
     */
    public ScopePath createScopePath() {
        return new ScopePathImpl();
    }

    /**
     * Create an instance of {@link ExternalIdReference }
     * 
     */
    public ExternalIdReference createExternalIdReference() {
        return new ExternalIdReferenceImpl();
    }

    /**
     * Create an instance of {@link FundingExternalIdentifier }
     * 
     */
    public FundingExternalIdentifier createFundingExternalIdentifier() {
        return new FundingExternalIdentifierImpl();
    }

    /**
     * Create an instance of {@link ActivitiesVisibilityDefault }
     * 
     */
    public ActivitiesVisibilityDefault createActivitiesVisibilityDefault() {
        return new ActivitiesVisibilityDefaultImpl();
    }

    /**
     * Create an instance of {@link FundingList }
     * 
     */
    public FundingList createFundingList() {
        return new FundingListImpl();
    }

    /**
     * Create an instance of {@link Funding }
     * 
     */
    public Funding createFunding() {
        return new FundingImpl();
    }

    /**
     * Create an instance of {@link FundingTitle }
     * 
     */
    public FundingTitle createFundingTitle() {
        return new FundingTitleImpl();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new AmountImpl();
    }

    /**
     * Create an instance of {@link FundingExternalIdentifiers }
     * 
     */
    public FundingExternalIdentifiers createFundingExternalIdentifiers() {
        return new FundingExternalIdentifiersImpl();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new OrganizationImpl();
    }

    /**
     * Create an instance of {@link OrganizationAddress }
     * 
     */
    public OrganizationAddress createOrganizationAddress() {
        return new OrganizationAddressImpl();
    }

    /**
     * Create an instance of {@link DisambiguatedOrganization }
     * 
     */
    public DisambiguatedOrganization createDisambiguatedOrganization() {
        return new DisambiguatedOrganizationImpl();
    }

    /**
     * Create an instance of {@link DelegateSummary }
     * 
     */
    public DelegateSummary createDelegateSummary() {
        return new DelegateSummaryImpl();
    }

    /**
     * Create an instance of {@link SendChangeNotifications }
     * 
     */
    public SendChangeNotifications createSendChangeNotifications() {
        return new SendChangeNotificationsImpl();
    }

    /**
     * Create an instance of {@link OrcidPreferences }
     * 
     */
    public OrcidPreferences createOrcidPreferences() {
        return new OrcidPreferencesImpl();
    }

    /**
     * Create an instance of {@link RelevancyScore }
     * 
     */
    public RelevancyScore createRelevancyScore() {
        return new RelevancyScoreImpl();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new EmailImpl();
    }

    /**
     * Create an instance of {@link SubmissionDate }
     * 
     */
    public SubmissionDate createSubmissionDate() {
        return new SubmissionDateImpl();
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     */
    public Preferences createPreferences() {
        return new PreferencesImpl();
    }

    /**
     * Create an instance of {@link SendOrcidNews }
     * 
     */
    public SendOrcidNews createSendOrcidNews() {
        return new SendOrcidNewsImpl();
    }

    /**
     * Create an instance of {@link DeveloperToolsEnabled }
     * 
     */
    public DeveloperToolsEnabled createDeveloperToolsEnabled() {
        return new DeveloperToolsEnabledImpl();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new AddressImpl();
    }

    /**
     * Create an instance of {@link Biography }
     * 
     */
    public Biography createBiography() {
        return new BiographyImpl();
    }

    /**
     * Create an instance of {@link DelegationDetails }
     * 
     */
    public DelegationDetails createDelegationDetails() {
        return new DelegationDetailsImpl();
    }

    /**
     * Create an instance of {@link ExternalIdUrl }
     * 
     */
    public ExternalIdUrl createExternalIdUrl() {
        return new ExternalIdUrlImpl();
    }

    /**
     * Create an instance of {@link CompletionDate }
     * 
     */
    public CompletionDate createCompletionDate() {
        return new CompletionDateImpl();
    }

    /**
     * Create an instance of {@link OrcidMessage }
     * 
     */
    public OrcidMessage createOrcidMessage() {
        return new OrcidMessageImpl();
    }

    /**
     * Create an instance of {@link ErrorDesc }
     * 
     */
    public ErrorDesc createErrorDesc() {
        return new ErrorDescImpl();
    }

    /**
     * Create an instance of {@link OrcidSearchResults }
     * 
     */
    public OrcidSearchResults createOrcidSearchResults() {
        return new OrcidSearchResultsImpl();
    }

    /**
     * Create an instance of {@link OrcidSearchResult }
     * 
     */
    public OrcidSearchResult createOrcidSearchResult() {
        return new OrcidSearchResultImpl();
    }

    /**
     * Create an instance of {@link OrcidProfile }
     * 
     */
    public OrcidProfile createOrcidProfile() {
        return new OrcidProfileImpl();
    }

    /**
     * Create an instance of {@link OrcidHistory }
     * 
     */
    public OrcidHistory createOrcidHistory() {
        return new OrcidHistoryImpl();
    }

    /**
     * Create an instance of {@link DeactivationDate }
     * 
     */
    public DeactivationDate createDeactivationDate() {
        return new DeactivationDateImpl();
    }

    /**
     * Create an instance of {@link OrcidBio }
     * 
     */
    public OrcidBio createOrcidBio() {
        return new OrcidBioImpl();
    }

    /**
     * Create an instance of {@link PersonalDetails }
     * 
     */
    public PersonalDetails createPersonalDetails() {
        return new PersonalDetailsImpl();
    }

    /**
     * Create an instance of {@link OtherNames }
     * 
     */
    public OtherNames createOtherNames() {
        return new OtherNamesImpl();
    }

    /**
     * Create an instance of {@link ResearcherUrls }
     * 
     */
    public ResearcherUrls createResearcherUrls() {
        return new ResearcherUrlsImpl();
    }

    /**
     * Create an instance of {@link ResearcherUrl }
     * 
     */
    public ResearcherUrl createResearcherUrl() {
        return new ResearcherUrlImpl();
    }

    /**
     * Create an instance of {@link ContactDetails }
     * 
     */
    public ContactDetails createContactDetails() {
        return new ContactDetailsImpl();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new KeywordsImpl();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new KeywordImpl();
    }

    /**
     * Create an instance of {@link ExternalIdentifiers }
     * 
     */
    public ExternalIdentifiers createExternalIdentifiers() {
        return new ExternalIdentifiersImpl();
    }

    /**
     * Create an instance of {@link ExternalIdentifier }
     * 
     */
    public ExternalIdentifier createExternalIdentifier() {
        return new ExternalIdentifierImpl();
    }

    /**
     * Create an instance of {@link ExternalIdCommonName }
     * 
     */
    public ExternalIdCommonName createExternalIdCommonName() {
        return new ExternalIdCommonNameImpl();
    }

    /**
     * Create an instance of {@link Delegation }
     * 
     */
    public Delegation createDelegation() {
        return new DelegationImpl();
    }

    /**
     * Create an instance of {@link GivenPermissionTo }
     * 
     */
    public GivenPermissionTo createGivenPermissionTo() {
        return new GivenPermissionToImpl();
    }

    /**
     * Create an instance of {@link GivenPermissionBy }
     * 
     */
    public GivenPermissionBy createGivenPermissionBy() {
        return new GivenPermissionByImpl();
    }

    /**
     * Create an instance of {@link Applications }
     * 
     */
    public Applications createApplications() {
        return new ApplicationsImpl();
    }

    /**
     * Create an instance of {@link OrcidActivities }
     * 
     */
    public OrcidActivities createOrcidActivities() {
        return new OrcidActivitiesImpl();
    }

    /**
     * Create an instance of {@link Affiliations }
     * 
     */
    public Affiliations createAffiliations() {
        return new AffiliationsImpl();
    }

    /**
     * Create an instance of {@link Affiliation }
     * 
     */
    public Affiliation createAffiliation() {
        return new AffiliationImpl();
    }

    /**
     * Create an instance of {@link OrcidInternal }
     * 
     */
    public OrcidInternal createOrcidInternal() {
        return new OrcidInternalImpl();
    }

    /**
     * Create an instance of {@link Orcid }
     * 
     */
    public Orcid createOrcid() {
        return new OrcidImpl();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "source-orcid")
    public JAXBElement<OrcidId> createSourceOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_SourceOrcid_QNAME, ((Class) OrcidIdImpl.class), null, ((OrcidIdImpl) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "send-email-frequency-days")
    public JAXBElement<String> createSendEmailFrequencyDays(String value) {
        return new JAXBElement<String>(_SendEmailFrequencyDays_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "short-description")
    public JAXBElement<String> createShortDescription(String value) {
        return new JAXBElement<String>(_ShortDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "orcid-identifier")
    public JAXBElement<OrcidId> createOrcidIdentifier(OrcidId value) {
        return new JAXBElement<OrcidId>(_OrcidIdentifier_QNAME, ((Class) OrcidIdImpl.class), null, ((OrcidIdImpl) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "locale")
    public JAXBElement<String> createLocale(String value) {
        return new JAXBElement<String>(_Locale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-external-identifier-type")
    public JAXBElement<String> createWorkExternalIdentifierType(String value) {
        return new JAXBElement<String>(_WorkExternalIdentifierType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-type")
    public JAXBElement<String> createWorkType(String value) {
        return new JAXBElement<String>(_WorkType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "funding-external-identifier-type")
    public JAXBElement<String> createFundingExternalIdentifierType(String value) {
        return new JAXBElement<String>(_FundingExternalIdentifierType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "message-version")
    public JAXBElement<String> createMessageVersion(String value) {
        return new JAXBElement<String>(_MessageVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "funding-contributor-role")
    public JAXBElement<String> createFundingContributorRole(String value) {
        return new JAXBElement<String>(_FundingContributorRole_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "application-orcid")
    public JAXBElement<OrcidId> createApplicationOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_ApplicationOrcid_QNAME, ((Class) OrcidIdImpl.class), null, ((OrcidIdImpl) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "send-member-update-requests")
    public JAXBElement<Boolean> createSendMemberUpdateRequests(Boolean value) {
        return new JAXBElement<Boolean>(_SendMemberUpdateRequests_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "disambiguated-organization-identifier")
    public JAXBElement<String> createDisambiguatedOrganizationIdentifier(String value) {
        return new JAXBElement<String>(_DisambiguatedOrganizationIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "organization-defined-type")
    public JAXBElement<String> createOrganizationDefinedType(String value) {
        return new JAXBElement<String>(_OrganizationDefinedType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "funding-type")
    public JAXBElement<String> createFundingType(String value) {
        return new JAXBElement<String>(_FundingType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "salesforce-id")
    public JAXBElement<String> createSalesforceId(String value) {
        return new JAXBElement<String>(_SalesforceId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "contributor-sequence")
    public JAXBElement<String> createContributorSequence(String value) {
        return new JAXBElement<String>(_ContributorSequence_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "disambiguation-source")
    public JAXBElement<String> createDisambiguationSource(String value) {
        return new JAXBElement<String>(_DisambiguationSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "contributor-orcid")
    public JAXBElement<OrcidId> createContributorOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_ContributorOrcid_QNAME, ((Class) OrcidIdImpl.class), null, ((OrcidIdImpl) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "host")
    public JAXBElement<String> createHost(String value) {
        return new JAXBElement<String>(_Host_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "path")
    public JAXBElement<String> createPath(String value) {
        return new JAXBElement<String>(_Path_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-external-identifier-id")
    public JAXBElement<String> createWorkExternalIdentifierId(String value) {
        return new JAXBElement<String>(_WorkExternalIdentifierId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "contributor-role")
    public JAXBElement<String> createContributorRole(String value) {
        return new JAXBElement<String>(_ContributorRole_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-source")
    public JAXBElement<OrcidId> createWorkSource(OrcidId value) {
        return new JAXBElement<OrcidId>(_WorkSource_QNAME, ((Class) OrcidIdImpl.class), null, ((OrcidIdImpl) value));
    }

}
