//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}personal-details" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}biography" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}researcher-urls" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}contact-details" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}keywords" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}external-identifiers" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}delegation" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}applications" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}scope"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface OrcidBio {


    /**
     * Gets the value of the personalDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalDetails }
     *     
     */
    PersonalDetails getPersonalDetails();

    /**
     * Sets the value of the personalDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalDetails }
     *     
     */
    void setPersonalDetails(PersonalDetails value);

    /**
     * Gets the value of the biography property.
     * 
     * @return
     *     possible object is
     *     {@link Biography }
     *     
     */
    Biography getBiography();

    /**
     * Sets the value of the biography property.
     * 
     * @param value
     *     allowed object is
     *     {@link Biography }
     *     
     */
    void setBiography(Biography value);

    /**
     * Gets the value of the researcherUrls property.
     * 
     * @return
     *     possible object is
     *     {@link ResearcherUrls }
     *     
     */
    ResearcherUrls getResearcherUrls();

    /**
     * Sets the value of the researcherUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearcherUrls }
     *     
     */
    void setResearcherUrls(ResearcherUrls value);

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDetails }
     *     
     */
    ContactDetails getContactDetails();

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDetails }
     *     
     */
    void setContactDetails(ContactDetails value);

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link Keywords }
     *     
     */
    Keywords getKeywords();

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keywords }
     *     
     */
    void setKeywords(Keywords value);

    /**
     * Gets the value of the externalIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalIdentifiers }
     *     
     */
    ExternalIdentifiers getExternalIdentifiers();

    /**
     * Sets the value of the externalIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIdentifiers }
     *     
     */
    void setExternalIdentifiers(ExternalIdentifiers value);

    /**
     * Gets the value of the delegation property.
     * 
     * @return
     *     possible object is
     *     {@link Delegation }
     *     
     */
    Delegation getDelegation();

    /**
     * Sets the value of the delegation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delegation }
     *     
     */
    void setDelegation(Delegation value);

    /**
     * Gets the value of the applications property.
     * 
     * @return
     *     possible object is
     *     {@link Applications }
     *     
     */
    Applications getApplications();

    /**
     * Sets the value of the applications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Applications }
     *     
     */
    void setApplications(Applications value);

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link Scope }
     *     
     */
    Scope getScope();

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scope }
     *     
     */
    void setScope(Scope value);

}
