//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-identifier" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-deprecated" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-preferences" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-history" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-bio" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-activities" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-internal" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.orcid.org/ns/orcid}orcid-type" default="user" />
 *       &lt;attribute name="client-type" type="{http://www.orcid.org/ns/orcid}client-type" />
 *       &lt;attribute name="group-type" type="{http://www.orcid.org/ns/orcid}group-type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface OrcidProfile {


    /**
     * Gets the value of the orcidIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidId }
     *     
     */
    OrcidId getOrcidIdentifier();

    /**
     * Sets the value of the orcidIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidId }
     *     
     */
    void setOrcidIdentifier(OrcidId value);

    /**
     * Gets the value of the orcidDeprecated property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidDeprecated }
     *     
     */
    OrcidDeprecated getOrcidDeprecated();

    /**
     * Sets the value of the orcidDeprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidDeprecated }
     *     
     */
    void setOrcidDeprecated(OrcidDeprecated value);

    /**
     * Gets the value of the orcidPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidPreferences }
     *     
     */
    OrcidPreferences getOrcidPreferences();

    /**
     * Sets the value of the orcidPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidPreferences }
     *     
     */
    void setOrcidPreferences(OrcidPreferences value);

    /**
     * Gets the value of the orcidHistory property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidHistory }
     *     
     */
    OrcidHistory getOrcidHistory();

    /**
     * Sets the value of the orcidHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidHistory }
     *     
     */
    void setOrcidHistory(OrcidHistory value);

    /**
     * Gets the value of the orcidBio property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidBio }
     *     
     */
    OrcidBio getOrcidBio();

    /**
     * Sets the value of the orcidBio property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidBio }
     *     
     */
    void setOrcidBio(OrcidBio value);

    /**
     * Gets the value of the orcidActivities property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidActivities }
     *     
     */
    OrcidActivities getOrcidActivities();

    /**
     * Sets the value of the orcidActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidActivities }
     *     
     */
    void setOrcidActivities(OrcidActivities value);

    /**
     * Gets the value of the orcidInternal property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidInternal }
     *     
     */
    OrcidInternal getOrcidInternal();

    /**
     * Sets the value of the orcidInternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidInternal }
     *     
     */
    void setOrcidInternal(OrcidInternal value);

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidType }
     *     
     */
    OrcidType getType();

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidType }
     *     
     */
    void setType(OrcidType value);

    /**
     * Gets the value of the clientType property.
     * 
     * @return
     *     possible object is
     *     {@link ClientType }
     *     
     */
    ClientType getClientType();

    /**
     * Sets the value of the clientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientType }
     *     
     */
    void setClientType(ClientType value);

    /**
     * Gets the value of the groupType property.
     * 
     * @return
     *     possible object is
     *     {@link GroupType }
     *     
     */
    GroupType getGroupType();

    /**
     * Sets the value of the groupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupType }
     *     
     */
    void setGroupType(GroupType value);

}
