//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}affiliations" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid-works" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}funding-list" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface OrcidActivities {


    /**
     * Gets the value of the affiliations property.
     * 
     * @return
     *     possible object is
     *     {@link Affiliations }
     *     
     */
    Affiliations getAffiliations();

    /**
     * Sets the value of the affiliations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Affiliations }
     *     
     */
    void setAffiliations(Affiliations value);

    /**
     * Gets the value of the orcidWorks property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidWorks }
     *     
     */
    OrcidWorks getOrcidWorks();

    /**
     * Sets the value of the orcidWorks property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidWorks }
     *     
     */
    void setOrcidWorks(OrcidWorks value);

    /**
     * Gets the value of the fundingList property.
     * 
     * @return
     *     possible object is
     *     {@link FundingList }
     *     
     */
    FundingList getFundingList();

    /**
     * Sets the value of the fundingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingList }
     *     
     */
    void setFundingList(FundingList value);

}
