//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}encrypted-password"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}security-question-id" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}encrypted-security-answer" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}encrypted-verification-code"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface SecurityDetails {


    /**
     * Gets the value of the encryptedPassword property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptedPassword }
     *     
     */
    EncryptedPassword getEncryptedPassword();

    /**
     * Sets the value of the encryptedPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptedPassword }
     *     
     */
    void setEncryptedPassword(EncryptedPassword value);

    /**
     * Gets the value of the securityQuestionId property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityQuestionId }
     *     
     */
    SecurityQuestionId getSecurityQuestionId();

    /**
     * Sets the value of the securityQuestionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityQuestionId }
     *     
     */
    void setSecurityQuestionId(SecurityQuestionId value);

    /**
     * Gets the value of the encryptedSecurityAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptedSecurityAnswer }
     *     
     */
    EncryptedSecurityAnswer getEncryptedSecurityAnswer();

    /**
     * Sets the value of the encryptedSecurityAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptedSecurityAnswer }
     *     
     */
    void setEncryptedSecurityAnswer(EncryptedSecurityAnswer value);

    /**
     * Gets the value of the encryptedVerificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptedVerificationCode }
     *     
     */
    EncryptedVerificationCode getEncryptedVerificationCode();

    /**
     * Sets the value of the encryptedVerificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptedVerificationCode }
     *     
     */
    void setEncryptedVerificationCode(EncryptedVerificationCode value);

}
