//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.orcid.org/ns/orcid}source-orcid"/>
 *           &lt;element ref="{http://www.orcid.org/ns/orcid}source-client-id"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}source-name" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}source-date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface Source {


    /**
     * Gets the value of the sourceClientId property.
     * 
     * @return
     *     possible object is
     *     {@link SourceClientId }
     *     
     */
    SourceClientId getSourceClientId();

    /**
     * Sets the value of the sourceClientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceClientId }
     *     
     */
    void setSourceClientId(SourceClientId value);

    /**
     * Gets the value of the sourceOrcid property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidId }
     *     
     */
    OrcidId getSourceOrcid();

    /**
     * Sets the value of the sourceOrcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidId }
     *     
     */
    void setSourceOrcid(OrcidId value);

    /**
     * Gets the value of the sourceName property.
     * 
     * @return
     *     possible object is
     *     {@link SourceName }
     *     
     */
    SourceName getSourceName();

    /**
     * Sets the value of the sourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceName }
     *     
     */
    void setSourceName(SourceName value);

    /**
     * Gets the value of the sourceDate property.
     * 
     * @return
     *     possible object is
     *     {@link SourceDate }
     *     
     */
    SourceDate getSourceDate();

    /**
     * Sets the value of the sourceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceDate }
     *     
     */
    void setSourceDate(SourceDate value);

}
