//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}given-permission-to" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}given-permission-by" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}visibility"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface Delegation {


    /**
     * Gets the value of the givenPermissionTo property.
     * 
     * @return
     *     possible object is
     *     {@link GivenPermissionTo }
     *     
     */
    GivenPermissionTo getGivenPermissionTo();

    /**
     * Sets the value of the givenPermissionTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GivenPermissionTo }
     *     
     */
    void setGivenPermissionTo(GivenPermissionTo value);

    /**
     * Gets the value of the givenPermissionBy property.
     * 
     * @return
     *     possible object is
     *     {@link GivenPermissionBy }
     *     
     */
    GivenPermissionBy getGivenPermissionBy();

    /**
     * Sets the value of the givenPermissionBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link GivenPermissionBy }
     *     
     */
    void setGivenPermissionBy(GivenPermissionBy value);

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Visibility }
     *     
     */
    Visibility getVisibility();

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Visibility }
     *     
     */
    void setVisibility(Visibility value);

}
