//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}external-id-common-name" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}external-id-reference" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}external-id-url" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}source" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface ExternalIdentifier {


    /**
     * Gets the value of the externalIdCommonName property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalIdCommonName }
     *     
     */
    ExternalIdCommonName getExternalIdCommonName();

    /**
     * Sets the value of the externalIdCommonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIdCommonName }
     *     
     */
    void setExternalIdCommonName(ExternalIdCommonName value);

    /**
     * Gets the value of the externalIdReference property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalIdReference }
     *     
     */
    ExternalIdReference getExternalIdReference();

    /**
     * Sets the value of the externalIdReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIdReference }
     *     
     */
    void setExternalIdReference(ExternalIdReference value);

    /**
     * Gets the value of the externalIdUrl property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalIdUrl }
     *     
     */
    ExternalIdUrl getExternalIdUrl();

    /**
     * Sets the value of the externalIdUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIdUrl }
     *     
     */
    void setExternalIdUrl(ExternalIdUrl value);

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    Source getSource();

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    void setSource(Source value);

}
