//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="creation-method" type="{http://www.orcid.org/ns/orcid}creation-method" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}completion-date" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}submission-date" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}last-modified-date" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}claimed" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}source" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}deactivation-date" minOccurs="0"/>
 *         &lt;element name="verified-email" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="verified-primary-email" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}visibility"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface OrcidHistory {


    /**
     * Gets the value of the creationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CreationMethod }
     *     
     */
    CreationMethod getCreationMethod();

    /**
     * Sets the value of the creationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationMethod }
     *     
     */
    void setCreationMethod(CreationMethod value);

    /**
     * Gets the value of the completionDate property.
     * 
     * @return
     *     possible object is
     *     {@link CompletionDate }
     *     
     */
    CompletionDate getCompletionDate();

    /**
     * Sets the value of the completionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompletionDate }
     *     
     */
    void setCompletionDate(CompletionDate value);

    /**
     * Gets the value of the submissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link SubmissionDate }
     *     
     */
    SubmissionDate getSubmissionDate();

    /**
     * Sets the value of the submissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmissionDate }
     *     
     */
    void setSubmissionDate(SubmissionDate value);

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link LastModifiedDate }
     *     
     */
    LastModifiedDate getLastModifiedDate();

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastModifiedDate }
     *     
     */
    void setLastModifiedDate(LastModifiedDate value);

    /**
     * Gets the value of the claimed property.
     * 
     * @return
     *     possible object is
     *     {@link Claimed }
     *     
     */
    Claimed getClaimed();

    /**
     * Sets the value of the claimed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Claimed }
     *     
     */
    void setClaimed(Claimed value);

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    Source getSource();

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    void setSource(Source value);

    /**
     * Gets the value of the deactivationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DeactivationDate }
     *     
     */
    DeactivationDate getDeactivationDate();

    /**
     * Sets the value of the deactivationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeactivationDate }
     *     
     */
    void setDeactivationDate(DeactivationDate value);

    /**
     * Gets the value of the verifiedEmail property.
     * 
     */
    boolean isVerifiedEmail();

    /**
     * Sets the value of the verifiedEmail property.
     * 
     */
    void setVerifiedEmail(boolean value);

    /**
     * Gets the value of the verifiedPrimaryEmail property.
     * 
     */
    boolean isVerifiedPrimaryEmail();

    /**
     * Sets the value of the verifiedPrimaryEmail property.
     * 
     */
    void setVerifiedPrimaryEmail(boolean value);

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Visibility }
     *     
     */
    Visibility getVisibility();

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Visibility }
     *     
     */
    void setVisibility(Visibility value);

}
