//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;

import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}work-title" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}journal-title" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}short-description" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}work-citation" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}work-type"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}publication-date" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}work-external-identifiers" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}url" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}work-contributors" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}source" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}created-date" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}last-modified-date" minOccurs="0"/>
 *         &lt;element name="language-code" type="{http://www.orcid.org/ns/orcid}language-code" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}country" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}visibility"/>
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}put-code"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface OrcidWork {


    /**
     * Gets the value of the workTitle property.
     * 
     * @return
     *     possible object is
     *     {@link WorkTitle }
     *     
     */
    WorkTitle getWorkTitle();

    /**
     * Sets the value of the workTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkTitle }
     *     
     */
    void setWorkTitle(WorkTitle value);

    /**
     * Gets the value of the journalTitle property.
     * 
     * @return
     *     possible object is
     *     {@link JournalTitle }
     *     
     */
    JournalTitle getJournalTitle();

    /**
     * Sets the value of the journalTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalTitle }
     *     
     */
    void setJournalTitle(JournalTitle value);

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getShortDescription();

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setShortDescription(String value);

    /**
     * Gets the value of the workCitation property.
     * 
     * @return
     *     possible object is
     *     {@link WorkCitation }
     *     
     */
    WorkCitation getWorkCitation();

    /**
     * Sets the value of the workCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkCitation }
     *     
     */
    void setWorkCitation(WorkCitation value);

    /**
     * Gets the value of the workType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getWorkType();

    /**
     * Sets the value of the workType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setWorkType(String value);

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationDate }
     *     
     */
    PublicationDate getPublicationDate();

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationDate }
     *     
     */
    void setPublicationDate(PublicationDate value);

    /**
     * Gets the value of the workExternalIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link WorkExternalIdentifiers }
     *     
     */
    WorkExternalIdentifiers getWorkExternalIdentifiers();

    /**
     * Sets the value of the workExternalIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkExternalIdentifiers }
     *     
     */
    void setWorkExternalIdentifiers(WorkExternalIdentifiers value);

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link Url }
     *     
     */
    Url getUrl();

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link Url }
     *     
     */
    void setUrl(Url value);

    /**
     * Gets the value of the workContributors property.
     * 
     * @return
     *     possible object is
     *     {@link WorkContributors }
     *     
     */
    WorkContributors getWorkContributors();

    /**
     * Sets the value of the workContributors property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkContributors }
     *     
     */
    void setWorkContributors(WorkContributors value);

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    Source getSource();

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    void setSource(Source value);

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link CreatedDate }
     *     
     */
    CreatedDate getCreatedDate();

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreatedDate }
     *     
     */
    void setCreatedDate(CreatedDate value);

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link LastModifiedDate }
     *     
     */
    LastModifiedDate getLastModifiedDate();

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastModifiedDate }
     *     
     */
    void setLastModifiedDate(LastModifiedDate value);

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageCode }
     *     
     */
    LanguageCode getLanguageCode();

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageCode }
     *     
     */
    void setLanguageCode(LanguageCode value);

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    Country getCountry();

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    void setCountry(Country value);

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Visibility }
     *     
     */
    Visibility getVisibility();

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Visibility }
     *     
     */
    void setVisibility(Visibility value);

    /**
     * Gets the value of the putCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    BigInteger getPutCode();

    /**
     * Sets the value of the putCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    void setPutCode(BigInteger value);

}
