//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:57:48 PM BST 
//


package org.springframework.social.orcid.jaxb.beans;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-email-frequency-days"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-change-notifications"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-orcid-news"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-member-update-requests"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}activities-visibility-default"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}developer-tools-enabled" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface Preferences {


    /**
     * Gets the value of the sendEmailFrequencyDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getSendEmailFrequencyDays();

    /**
     * Sets the value of the sendEmailFrequencyDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setSendEmailFrequencyDays(String value);

    /**
     * Gets the value of the sendChangeNotifications property.
     * 
     * @return
     *     possible object is
     *     {@link SendChangeNotifications }
     *     
     */
    SendChangeNotifications getSendChangeNotifications();

    /**
     * Sets the value of the sendChangeNotifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendChangeNotifications }
     *     
     */
    void setSendChangeNotifications(SendChangeNotifications value);

    /**
     * Gets the value of the sendOrcidNews property.
     * 
     * @return
     *     possible object is
     *     {@link SendOrcidNews }
     *     
     */
    SendOrcidNews getSendOrcidNews();

    /**
     * Sets the value of the sendOrcidNews property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendOrcidNews }
     *     
     */
    void setSendOrcidNews(SendOrcidNews value);

    /**
     * Gets the value of the sendMemberUpdateRequests property.
     * 
     */
    boolean isSendMemberUpdateRequests();

    /**
     * Sets the value of the sendMemberUpdateRequests property.
     * 
     */
    void setSendMemberUpdateRequests(boolean value);

    /**
     * Gets the value of the activitiesVisibilityDefault property.
     * 
     * @return
     *     possible object is
     *     {@link ActivitiesVisibilityDefault }
     *     
     */
    ActivitiesVisibilityDefault getActivitiesVisibilityDefault();

    /**
     * Sets the value of the activitiesVisibilityDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivitiesVisibilityDefault }
     *     
     */
    void setActivitiesVisibilityDefault(ActivitiesVisibilityDefault value);

    /**
     * Gets the value of the developerToolsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link DeveloperToolsEnabled }
     *     
     */
    DeveloperToolsEnabled getDeveloperToolsEnabled();

    /**
     * Sets the value of the developerToolsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeveloperToolsEnabled }
     *     
     */
    void setDeveloperToolsEnabled(DeveloperToolsEnabled value);

}
